/* GameMessage.c generated by valac 0.12.0, the Vala compiler
 * generated from GameMessage.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MESSAGE (message_get_type ())
#define MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MESSAGE, Message))
#define MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MESSAGE, MessageClass))
#define IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MESSAGE))
#define IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MESSAGE))
#define MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MESSAGE, MessageClass))

typedef struct _Message Message;
typedef struct _MessageClass MessageClass;
typedef struct _MessagePrivate MessagePrivate;

#define TYPE_GAME_MESSAGE (game_message_get_type ())
#define GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_MESSAGE, GameMessage))
#define GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_MESSAGE, GameMessageClass))
#define IS_GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_MESSAGE))
#define IS_GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_MESSAGE))
#define GAME_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_MESSAGE, GameMessageClass))

typedef struct _GameMessage GameMessage;
typedef struct _GameMessageClass GameMessageClass;
typedef struct _GameMessagePrivate GameMessagePrivate;

#define TYPE_INITIATE_MESSAGE (initiate_message_get_type ())
#define INITIATE_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INITIATE_MESSAGE, InitiateMessage))
#define INITIATE_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_INITIATE_MESSAGE, InitiateMessageClass))
#define IS_INITIATE_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INITIATE_MESSAGE))
#define IS_INITIATE_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_INITIATE_MESSAGE))
#define INITIATE_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_INITIATE_MESSAGE, InitiateMessageClass))

typedef struct _InitiateMessage InitiateMessage;
typedef struct _InitiateMessageClass InitiateMessageClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_HOST_MESSAGE (host_message_get_type ())
#define HOST_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HOST_MESSAGE, HostMessage))
#define HOST_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HOST_MESSAGE, HostMessageClass))
#define IS_HOST_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HOST_MESSAGE))
#define IS_HOST_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HOST_MESSAGE))
#define HOST_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HOST_MESSAGE, HostMessageClass))

typedef struct _HostMessage HostMessage;
typedef struct _HostMessageClass HostMessageClass;

#define TYPE_PLAYER_MESSAGE (player_message_get_type ())
#define PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PLAYER_MESSAGE, PlayerMessage))
#define PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PLAYER_MESSAGE, PlayerMessageClass))
#define IS_PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PLAYER_MESSAGE))
#define IS_PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PLAYER_MESSAGE))
#define PLAYER_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PLAYER_MESSAGE, PlayerMessageClass))

typedef struct _PlayerMessage PlayerMessage;
typedef struct _PlayerMessageClass PlayerMessageClass;

struct _Message {
	GObject parent_instance;
	MessagePrivate * priv;
};

struct _MessageClass {
	GObjectClass parent_class;
};

struct _GameMessage {
	Message parent_instance;
	GameMessagePrivate * priv;
};

struct _GameMessageClass {
	MessageClass parent_class;
};

struct _GameMessagePrivate {
	guint32 type;
};


static gpointer game_message_parent_class = NULL;

GType message_get_type (void) G_GNUC_CONST;
GType game_message_get_type (void) G_GNUC_CONST;
#define GAME_MESSAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GAME_MESSAGE, GameMessagePrivate))
enum  {
	GAME_MESSAGE_DUMMY_PROPERTY
};
#define GAME_MESSAGE_INIT ((guint32) 0x1)
#define GAME_MESSAGE_INIT_REPLY ((guint32) 0x2)
#define GAME_MESSAGE_HOST ((guint32) 0x10)
#define GAME_MESSAGE_PLAYER ((guint32) 0x20)
GameMessage* game_message_new (GArray* chunks, guint32 type);
GameMessage* game_message_construct (GType object_type, GArray* chunks, guint32 type);
guint8* int_to_data (guint32 n, int* result_length1);
Message* message_new (guint8* data, int data_length1);
Message* message_construct (GType object_type, guint8* data, int data_length1);
GameMessage* game_message_parse (Message* message);
guint32 game_message_get_uint_at (guint8* data, int data_length1, gint pos);
guint8* message_get_data (Message* self, int* result_length1);
InitiateMessage* initiate_message_new (guint8* data, int data_length1, guint32 type);
InitiateMessage* initiate_message_construct (GType object_type, guint8* data, int data_length1, guint32 type);
GType initiate_message_get_type (void) G_GNUC_CONST;
GType host_message_get_type (void) G_GNUC_CONST;
HostMessage* host_message_parse (guint8* data, int data_length1);
GType player_message_get_type (void) G_GNUC_CONST;
PlayerMessage* player_message_parse (guint8* data, int data_length1);
void message_set_data (Message* self, guint8* value, int value_length1);
gchar* game_message_get_string_at (guint8* data, int data_length1, guint32 pos, guint32 len);
static void game_message_finalize (GObject* obj);


GameMessage* game_message_construct (GType object_type, GArray* chunks, guint32 type) {
	GameMessage * self = NULL;
	gint _tmp0_;
	guint8* _tmp1_ = NULL;
	guint8* _tmp2_;
	gint _tmp2__length1;
	guint8* _tmp3_ = NULL;
	guint8* d;
	gint d_length1;
	gint _d_size_;
	g_return_val_if_fail (chunks != NULL, NULL);
	_tmp1_ = int_to_data (type, &_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp0_;
	g_array_insert_vals (chunks, (guint) 0, _tmp2_, (guint) 4);
	_tmp2_ = (g_free (_tmp2_), NULL);
	_tmp3_ = g_new0 (guint8, chunks->len);
	d = _tmp3_;
	d_length1 = chunks->len;
	_d_size_ = chunks->len;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp4_;
			_tmp4_ = TRUE;
			while (TRUE) {
				guint8 _tmp5_;
				if (!_tmp4_) {
					i++;
				}
				_tmp4_ = FALSE;
				if (!(i < chunks->len)) {
					break;
				}
				_tmp5_ = g_array_index (chunks, guint8, (guint) i);
				d[i] = _tmp5_;
			}
		}
	}
	self = (GameMessage*) message_construct (object_type, d, d_length1);
	self->priv->type = type;
	d = (g_free (d), NULL);
	return self;
}


GameMessage* game_message_new (GArray* chunks, guint32 type) {
	return game_message_construct (TYPE_GAME_MESSAGE, chunks, type);
}


GameMessage* game_message_parse (Message* message) {
	GameMessage* result = NULL;
	guint8* _tmp0_ = NULL;
	gint _tmp1_;
	guint32 _tmp2_;
	guint32 t;
	guint8* _tmp3_ = NULL;
	gint _tmp4_;
	guint8* _tmp5_ = NULL;
	guint8* data;
	gint data_length1;
	gint _data_size_;
	GameMessage* m;
	g_return_val_if_fail (message != NULL, NULL);
	_tmp0_ = message_get_data (message, &_tmp1_);
	_tmp2_ = game_message_get_uint_at (_tmp0_, _tmp1_, 0);
	t = _tmp2_;
	_tmp3_ = message_get_data (message, &_tmp4_);
	_tmp5_ = g_new0 (guint8, _tmp4_ - 4);
	data = _tmp5_;
	data_length1 = _tmp4_ - 4;
	_data_size_ = _tmp4_ - 4;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp6_;
			_tmp6_ = TRUE;
			while (TRUE) {
				guint8* _tmp7_ = NULL;
				gint _tmp8_;
				if (!_tmp6_) {
					i++;
				}
				_tmp6_ = FALSE;
				if (!(i < data_length1)) {
					break;
				}
				_tmp7_ = message_get_data (message, &_tmp8_);
				data[i] = _tmp7_[i + 4];
			}
		}
	}
	m = NULL;
	switch (t) {
		case GAME_MESSAGE_INIT:
		case GAME_MESSAGE_INIT_REPLY:
		{
			InitiateMessage* _tmp9_ = NULL;
			_tmp9_ = initiate_message_new (data, data_length1, t);
			_g_object_unref0 (m);
			m = (GameMessage*) _tmp9_;
			break;
		}
		case GAME_MESSAGE_HOST:
		{
			HostMessage* _tmp10_ = NULL;
			_tmp10_ = host_message_parse (data, data_length1);
			_g_object_unref0 (m);
			m = (GameMessage*) _tmp10_;
			break;
		}
		case GAME_MESSAGE_PLAYER:
		{
			PlayerMessage* _tmp11_ = NULL;
			_tmp11_ = player_message_parse (data, data_length1);
			_g_object_unref0 (m);
			m = (GameMessage*) _tmp11_;
			break;
		}
		default:
		break;
	}
	if (m != NULL) {
		guint8* _tmp12_ = NULL;
		gint _tmp13_;
		guint8* _tmp14_;
		_tmp12_ = message_get_data (message, &_tmp13_);
		_tmp14_ = _tmp12_;
		message_set_data ((Message*) m, _tmp14_, _tmp13_);
	}
	result = m;
	data = (g_free (data), NULL);
	return result;
}


guint32 game_message_get_uint_at (guint8* data, int data_length1, gint pos) {
	guint32 result = 0U;
	guint32 u;
	u = (guint32) 0;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < 4)) {
					break;
				}
				u = u + ((guint32) (data[pos + i] << (8 * (3 - i))));
			}
		}
	}
	result = u;
	return result;
}


gchar* game_message_get_string_at (guint8* data, int data_length1, guint32 pos, guint32 len) {
	gchar* result = NULL;
	guint8* _tmp0_ = NULL;
	guint8* d;
	gint d_length1;
	gint _d_size_;
	gchar* _tmp2_;
	_tmp0_ = g_new0 (guint8, len);
	d = _tmp0_;
	d_length1 = len;
	_d_size_ = len;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				if (!_tmp1_) {
					i++;
				}
				_tmp1_ = FALSE;
				if (!(i < len)) {
					break;
				}
				d[i] = data[i + pos];
			}
		}
	}
	_tmp2_ = g_strdup ((const gchar*) d);
	result = _tmp2_;
	d = (g_free (d), NULL);
	return result;
}


static void game_message_class_init (GameMessageClass * klass) {
	game_message_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GameMessagePrivate));
	G_OBJECT_CLASS (klass)->finalize = game_message_finalize;
}


static void game_message_instance_init (GameMessage * self) {
	self->priv = GAME_MESSAGE_GET_PRIVATE (self);
}


static void game_message_finalize (GObject* obj) {
	GameMessage * self;
	self = GAME_MESSAGE (obj);
	G_OBJECT_CLASS (game_message_parent_class)->finalize (obj);
}


GType game_message_get_type (void) {
	static volatile gsize game_message_type_id__volatile = 0;
	if (g_once_init_enter (&game_message_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GameMessageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) game_message_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GameMessage), 0, (GInstanceInitFunc) game_message_instance_init, NULL };
		GType game_message_type_id;
		game_message_type_id = g_type_register_static (TYPE_MESSAGE, "GameMessage", &g_define_type_info, 0);
		g_once_init_leave (&game_message_type_id__volatile, game_message_type_id);
	}
	return game_message_type_id__volatile;
}



