/* PlayerMessage.c generated by valac 0.12.0, the Vala compiler
 * generated from PlayerMessage.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define TYPE_MESSAGE (message_get_type ())
#define MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MESSAGE, Message))
#define MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MESSAGE, MessageClass))
#define IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MESSAGE))
#define IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MESSAGE))
#define MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MESSAGE, MessageClass))

typedef struct _Message Message;
typedef struct _MessageClass MessageClass;
typedef struct _MessagePrivate MessagePrivate;

#define TYPE_GAME_MESSAGE (game_message_get_type ())
#define GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_MESSAGE, GameMessage))
#define GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_MESSAGE, GameMessageClass))
#define IS_GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_MESSAGE))
#define IS_GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_MESSAGE))
#define GAME_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_MESSAGE, GameMessageClass))

typedef struct _GameMessage GameMessage;
typedef struct _GameMessageClass GameMessageClass;
typedef struct _GameMessagePrivate GameMessagePrivate;

#define TYPE_PLAYER_MESSAGE (player_message_get_type ())
#define PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PLAYER_MESSAGE, PlayerMessage))
#define PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PLAYER_MESSAGE, PlayerMessageClass))
#define IS_PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PLAYER_MESSAGE))
#define IS_PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PLAYER_MESSAGE))
#define PLAYER_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PLAYER_MESSAGE, PlayerMessageClass))

typedef struct _PlayerMessage PlayerMessage;
typedef struct _PlayerMessageClass PlayerMessageClass;
typedef struct _PlayerMessagePrivate PlayerMessagePrivate;

#define TYPE_CALL_ACTION_MESSAGE (call_action_message_get_type ())
#define CALL_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CALL_ACTION_MESSAGE, CallActionMessage))
#define CALL_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CALL_ACTION_MESSAGE, CallActionMessageClass))
#define IS_CALL_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CALL_ACTION_MESSAGE))
#define IS_CALL_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CALL_ACTION_MESSAGE))
#define CALL_ACTION_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CALL_ACTION_MESSAGE, CallActionMessageClass))

typedef struct _CallActionMessage CallActionMessage;
typedef struct _CallActionMessageClass CallActionMessageClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_TURN_ACTION_MESSAGE (turn_action_message_get_type ())
#define TURN_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TURN_ACTION_MESSAGE, TurnActionMessage))
#define TURN_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TURN_ACTION_MESSAGE, TurnActionMessageClass))
#define IS_TURN_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TURN_ACTION_MESSAGE))
#define IS_TURN_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TURN_ACTION_MESSAGE))
#define TURN_ACTION_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TURN_ACTION_MESSAGE, TurnActionMessageClass))

typedef struct _TurnActionMessage TurnActionMessage;
typedef struct _TurnActionMessageClass TurnActionMessageClass;

struct _Message {
	GObject parent_instance;
	MessagePrivate * priv;
};

struct _MessageClass {
	GObjectClass parent_class;
};

struct _GameMessage {
	Message parent_instance;
	GameMessagePrivate * priv;
};

struct _GameMessageClass {
	MessageClass parent_class;
};

struct _PlayerMessage {
	GameMessage parent_instance;
	PlayerMessagePrivate * priv;
};

struct _PlayerMessageClass {
	GameMessageClass parent_class;
};

struct _PlayerMessagePrivate {
	guint32 _id;
};


static gpointer player_message_parent_class = NULL;

GType message_get_type (void) G_GNUC_CONST;
GType game_message_get_type (void) G_GNUC_CONST;
GType player_message_get_type (void) G_GNUC_CONST;
#define PLAYER_MESSAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PLAYER_MESSAGE, PlayerMessagePrivate))
enum  {
	PLAYER_MESSAGE_DUMMY_PROPERTY,
	PLAYER_MESSAGE_ID
};
#define PLAYER_MESSAGE_CALL_ACTION ((guint32) 0x1)
#define PLAYER_MESSAGE_TURN_ACTION ((guint32) 0x2)
PlayerMessage* player_message_new (GArray* chunks, guint32 type, guint32 id);
PlayerMessage* player_message_construct (GType object_type, GArray* chunks, guint32 type, guint32 id);
guint8* int_to_data (guint32 n, int* result_length1);
#define GAME_MESSAGE_PLAYER ((guint32) 0x20)
GameMessage* game_message_new (GArray* chunks, guint32 type);
GameMessage* game_message_construct (GType object_type, GArray* chunks, guint32 type);
static void player_message_set_id (PlayerMessage* self, guint32 value);
PlayerMessage* player_message_parse (guint8* data, int data_length1);
guint32 game_message_get_uint_at (guint8* data, int data_length1, gint pos);
CallActionMessage* call_action_message_new (guint8* data, int data_length1);
CallActionMessage* call_action_message_construct (GType object_type, guint8* data, int data_length1);
GType call_action_message_get_type (void) G_GNUC_CONST;
TurnActionMessage* turn_action_message_new (guint8* data, int data_length1);
TurnActionMessage* turn_action_message_construct (GType object_type, guint8* data, int data_length1);
GType turn_action_message_get_type (void) G_GNUC_CONST;
guint32 player_message_get_id (PlayerMessage* self);
static void player_message_finalize (GObject* obj);
static void _vala_player_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_player_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


PlayerMessage* player_message_construct (GType object_type, GArray* chunks, guint32 type, guint32 id) {
	PlayerMessage * self = NULL;
	gint _tmp0_;
	guint8* _tmp1_ = NULL;
	guint8* _tmp2_;
	gint _tmp2__length1;
	gint _tmp3_;
	guint8* _tmp4_ = NULL;
	guint8* _tmp5_;
	gint _tmp5__length1;
	g_return_val_if_fail (chunks != NULL, NULL);
	_tmp1_ = int_to_data (id, &_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp0_;
	g_array_insert_vals (chunks, (guint) 0, _tmp2_, (guint) 4);
	_tmp2_ = (g_free (_tmp2_), NULL);
	_tmp4_ = int_to_data (type, &_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp5__length1 = _tmp3_;
	g_array_insert_vals (chunks, (guint) 0, _tmp5_, (guint) 4);
	_tmp5_ = (g_free (_tmp5_), NULL);
	self = (PlayerMessage*) game_message_construct (object_type, chunks, GAME_MESSAGE_PLAYER);
	player_message_set_id (self, id);
	return self;
}


PlayerMessage* player_message_new (GArray* chunks, guint32 type, guint32 id) {
	return player_message_construct (TYPE_PLAYER_MESSAGE, chunks, type, id);
}


PlayerMessage* player_message_parse (guint8* data, int data_length1) {
	PlayerMessage* result = NULL;
	guint32 _tmp0_;
	guint32 t;
	guint32 _tmp1_;
	guint32 id;
	guint8* _tmp2_ = NULL;
	guint8* d;
	gint d_length1;
	gint _d_size_;
	PlayerMessage* msg;
	_tmp0_ = game_message_get_uint_at (data, data_length1, 0);
	t = _tmp0_;
	_tmp1_ = game_message_get_uint_at (data, data_length1, 4);
	id = _tmp1_;
	_tmp2_ = g_new0 (guint8, data_length1 - 8);
	d = _tmp2_;
	d_length1 = data_length1 - 8;
	_d_size_ = data_length1 - 8;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp3_;
			_tmp3_ = TRUE;
			while (TRUE) {
				if (!_tmp3_) {
					i++;
				}
				_tmp3_ = FALSE;
				if (!(i < d_length1)) {
					break;
				}
				d[i] = data[i + 8];
			}
		}
	}
	msg = NULL;
	switch (t) {
		case PLAYER_MESSAGE_CALL_ACTION:
		{
			CallActionMessage* _tmp4_ = NULL;
			_tmp4_ = call_action_message_new (d, d_length1);
			_g_object_unref0 (msg);
			msg = (PlayerMessage*) _tmp4_;
			break;
		}
		case PLAYER_MESSAGE_TURN_ACTION:
		{
			TurnActionMessage* _tmp5_ = NULL;
			_tmp5_ = turn_action_message_new (d, d_length1);
			_g_object_unref0 (msg);
			msg = (PlayerMessage*) _tmp5_;
			break;
		}
		default:
		break;
	}
	if (msg != NULL) {
		player_message_set_id (msg, id);
	}
	result = msg;
	d = (g_free (d), NULL);
	return result;
}


guint32 player_message_get_id (PlayerMessage* self) {
	guint32 result;
	g_return_val_if_fail (self != NULL, 0U);
	result = self->priv->_id;
	return result;
}


static void player_message_set_id (PlayerMessage* self, guint32 value) {
	g_return_if_fail (self != NULL);
	self->priv->_id = value;
	g_object_notify ((GObject *) self, "id");
}


static void player_message_class_init (PlayerMessageClass * klass) {
	player_message_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PlayerMessagePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_player_message_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_player_message_set_property;
	G_OBJECT_CLASS (klass)->finalize = player_message_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), PLAYER_MESSAGE_ID, g_param_spec_uint ("id", "id", "id", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void player_message_instance_init (PlayerMessage * self) {
	self->priv = PLAYER_MESSAGE_GET_PRIVATE (self);
}


static void player_message_finalize (GObject* obj) {
	PlayerMessage * self;
	self = PLAYER_MESSAGE (obj);
	G_OBJECT_CLASS (player_message_parent_class)->finalize (obj);
}


GType player_message_get_type (void) {
	static volatile gsize player_message_type_id__volatile = 0;
	if (g_once_init_enter (&player_message_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PlayerMessageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) player_message_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlayerMessage), 0, (GInstanceInitFunc) player_message_instance_init, NULL };
		GType player_message_type_id;
		player_message_type_id = g_type_register_static (TYPE_GAME_MESSAGE, "PlayerMessage", &g_define_type_info, 0);
		g_once_init_leave (&player_message_type_id__volatile, player_message_type_id);
	}
	return player_message_type_id__volatile;
}


static void _vala_player_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PlayerMessage * self;
	self = PLAYER_MESSAGE (object);
	switch (property_id) {
		case PLAYER_MESSAGE_ID:
		g_value_set_uint (value, player_message_get_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_player_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PlayerMessage * self;
	self = PLAYER_MESSAGE (object);
	switch (property_id) {
		case PLAYER_MESSAGE_ID:
		player_message_set_id (self, g_value_get_uint (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



