/* TurnActionMessage.c generated by valac 0.12.0, the Vala compiler
 * generated from TurnActionMessage.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <string.h>


#define TYPE_MESSAGE (message_get_type ())
#define MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MESSAGE, Message))
#define MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MESSAGE, MessageClass))
#define IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MESSAGE))
#define IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MESSAGE))
#define MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MESSAGE, MessageClass))

typedef struct _Message Message;
typedef struct _MessageClass MessageClass;
typedef struct _MessagePrivate MessagePrivate;

#define TYPE_GAME_MESSAGE (game_message_get_type ())
#define GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_MESSAGE, GameMessage))
#define GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_MESSAGE, GameMessageClass))
#define IS_GAME_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_MESSAGE))
#define IS_GAME_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_MESSAGE))
#define GAME_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_MESSAGE, GameMessageClass))

typedef struct _GameMessage GameMessage;
typedef struct _GameMessageClass GameMessageClass;
typedef struct _GameMessagePrivate GameMessagePrivate;

#define TYPE_PLAYER_MESSAGE (player_message_get_type ())
#define PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PLAYER_MESSAGE, PlayerMessage))
#define PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PLAYER_MESSAGE, PlayerMessageClass))
#define IS_PLAYER_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PLAYER_MESSAGE))
#define IS_PLAYER_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PLAYER_MESSAGE))
#define PLAYER_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PLAYER_MESSAGE, PlayerMessageClass))

typedef struct _PlayerMessage PlayerMessage;
typedef struct _PlayerMessageClass PlayerMessageClass;
typedef struct _PlayerMessagePrivate PlayerMessagePrivate;

#define TYPE_TURN_ACTION_MESSAGE (turn_action_message_get_type ())
#define TURN_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TURN_ACTION_MESSAGE, TurnActionMessage))
#define TURN_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TURN_ACTION_MESSAGE, TurnActionMessageClass))
#define IS_TURN_ACTION_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TURN_ACTION_MESSAGE))
#define IS_TURN_ACTION_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TURN_ACTION_MESSAGE))
#define TURN_ACTION_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TURN_ACTION_MESSAGE, TurnActionMessageClass))

typedef struct _TurnActionMessage TurnActionMessage;
typedef struct _TurnActionMessageClass TurnActionMessageClass;
typedef struct _TurnActionMessagePrivate TurnActionMessagePrivate;

#define TYPE_TURN_ACTION (turn_action_get_type ())
#define TURN_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TURN_ACTION, TurnAction))
#define TURN_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TURN_ACTION, TurnActionClass))
#define IS_TURN_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TURN_ACTION))
#define IS_TURN_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TURN_ACTION))
#define TURN_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TURN_ACTION, TurnActionClass))

typedef struct _TurnAction TurnAction;
typedef struct _TurnActionClass TurnActionClass;
#define _turn_action_unref0(var) ((var == NULL) ? NULL : (var = (turn_action_unref (var), NULL)))

#define TURN_ACTION_TYPE_TURN_ACTION_ENUM (turn_action_turn_action_enum_get_type ())
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))
#define _g_array_unref0(var) ((var == NULL) ? NULL : (var = (g_array_unref (var), NULL)))

struct _Message {
	GObject parent_instance;
	MessagePrivate * priv;
};

struct _MessageClass {
	GObjectClass parent_class;
};

struct _GameMessage {
	Message parent_instance;
	GameMessagePrivate * priv;
};

struct _GameMessageClass {
	MessageClass parent_class;
};

struct _PlayerMessage {
	GameMessage parent_instance;
	PlayerMessagePrivate * priv;
};

struct _PlayerMessageClass {
	GameMessageClass parent_class;
};

struct _TurnActionMessage {
	PlayerMessage parent_instance;
	TurnActionMessagePrivate * priv;
};

struct _TurnActionMessageClass {
	PlayerMessageClass parent_class;
};

struct _TurnActionMessagePrivate {
	TurnAction* _turn_action;
};

typedef enum  {
	TURN_ACTION_TURN_ACTION_ENUM_DISCARD,
	TURN_ACTION_TURN_ACTION_ENUM_CLOSED_KAN,
	TURN_ACTION_TURN_ACTION_ENUM_LATE_KAN,
	TURN_ACTION_TURN_ACTION_ENUM_RIICHI,
	TURN_ACTION_TURN_ACTION_ENUM_OPEN_RIICHI,
	TURN_ACTION_TURN_ACTION_ENUM_TSUMO
} TurnActionTurnActionEnum;


static gpointer turn_action_message_parent_class = NULL;

GType message_get_type (void) G_GNUC_CONST;
GType game_message_get_type (void) G_GNUC_CONST;
GType player_message_get_type (void) G_GNUC_CONST;
GType turn_action_message_get_type (void) G_GNUC_CONST;
gpointer turn_action_ref (gpointer instance);
void turn_action_unref (gpointer instance);
GParamSpec* param_spec_turn_action (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_turn_action (GValue* value, gpointer v_object);
void value_take_turn_action (GValue* value, gpointer v_object);
gpointer value_get_turn_action (const GValue* value);
GType turn_action_get_type (void) G_GNUC_CONST;
#define TURN_ACTION_MESSAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TURN_ACTION_MESSAGE, TurnActionMessagePrivate))
enum  {
	TURN_ACTION_MESSAGE_DUMMY_PROPERTY,
	TURN_ACTION_MESSAGE_TURN_ACTION
};
TurnActionMessage* turn_action_message_new (guint8* data, int data_length1);
TurnActionMessage* turn_action_message_construct (GType object_type, guint8* data, int data_length1);
Message* message_new_empty (void);
Message* message_construct_empty (GType object_type);
GType turn_action_turn_action_enum_get_type (void) G_GNUC_CONST;
static guint8* _uint8_dup (guint8* self);
guint32 game_message_get_uint_at (guint8* data, int data_length1, gint pos);
TurnAction* turn_action_new_set (TurnActionTurnActionEnum action, guint8* discard_tile, guint8* late_kan_tile, guint8* late_kan_pon, guint8* kan_tiles, int kan_tiles_length1);
TurnAction* turn_action_construct_set (GType object_type, TurnActionTurnActionEnum action, guint8* discard_tile, guint8* late_kan_tile, guint8* late_kan_pon, guint8* kan_tiles, int kan_tiles_length1);
static void turn_action_message_set_turn_action (TurnActionMessage* self, TurnAction* value);
TurnActionMessage* turn_action_message_new_message (guint32 id, TurnAction* action);
TurnActionMessage* turn_action_message_construct_message (GType object_type, guint32 id, TurnAction* action);
TurnActionTurnActionEnum turn_action_get_action (TurnAction* self);
guint8* turn_action_get_discard_tile (TurnAction* self);
guint8* turn_action_get_late_kan_tile (TurnAction* self);
guint8* turn_action_get_late_kan_pon (TurnAction* self);
guint8* turn_action_get_kan_tiles (TurnAction* self, int* result_length1);
guint8* int_to_data (guint32 n, int* result_length1);
#define PLAYER_MESSAGE_TURN_ACTION ((guint32) 0x2)
PlayerMessage* player_message_new (GArray* chunks, guint32 type, guint32 id);
PlayerMessage* player_message_construct (GType object_type, GArray* chunks, guint32 type, guint32 id);
TurnAction* turn_action_message_get_turn_action (TurnActionMessage* self);
static void turn_action_message_finalize (GObject* obj);
static void _vala_turn_action_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_turn_action_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static guint8* _uint8_dup (guint8* self) {
	guint8* dup;
	dup = g_new0 (guint8, 1);
	memcpy (dup, self, sizeof (guint8));
	return dup;
}


static gpointer __uint8_dup0 (gpointer self) {
	return self ? _uint8_dup (self) : NULL;
}


TurnActionMessage* turn_action_message_construct (GType object_type, guint8* data, int data_length1) {
	TurnActionMessage * self = NULL;
	TurnActionTurnActionEnum action;
	gint i;
	gboolean r;
	guint8* discard_tile;
	gint _tmp3_;
	guint8* late_kan_tile;
	gint _tmp7_;
	guint8* late_kan_pon;
	guint32 _tmp11_;
	guint32 len;
	guint8* kan_tiles;
	gint kan_tiles_length1;
	gint _kan_tiles_size_;
	TurnAction* _tmp14_ = NULL;
	TurnAction* _tmp15_;
	self = (TurnActionMessage*) message_construct_empty (object_type);
	action = (TurnActionTurnActionEnum) data[0];
	i = 2;
	r = data[1] != 0;
	discard_tile = NULL;
	if (r) {
		gint _tmp0_;
		guint8 _tmp1_;
		guint8* _tmp2_;
		_tmp0_ = i;
		i = _tmp0_ + 1;
		_tmp1_ = data[_tmp0_];
		_tmp2_ = __uint8_dup0 (&_tmp1_);
		_g_free0 (discard_tile);
		discard_tile = _tmp2_;
	}
	_tmp3_ = i;
	i = _tmp3_ + 1;
	r = data[_tmp3_] != 0;
	late_kan_tile = NULL;
	if (r) {
		gint _tmp4_;
		guint8 _tmp5_;
		guint8* _tmp6_;
		_tmp4_ = i;
		i = _tmp4_ + 1;
		_tmp5_ = data[_tmp4_];
		_tmp6_ = __uint8_dup0 (&_tmp5_);
		_g_free0 (late_kan_tile);
		late_kan_tile = _tmp6_;
	}
	_tmp7_ = i;
	i = _tmp7_ + 1;
	r = data[_tmp7_] != 0;
	late_kan_pon = NULL;
	if (r) {
		gint _tmp8_;
		guint8 _tmp9_;
		guint8* _tmp10_;
		_tmp8_ = i;
		i = _tmp8_ + 1;
		_tmp9_ = data[_tmp8_];
		_tmp10_ = __uint8_dup0 (&_tmp9_);
		_g_free0 (late_kan_pon);
		late_kan_pon = _tmp10_;
	}
	_tmp11_ = game_message_get_uint_at (data, data_length1, i);
	len = _tmp11_;
	i = i + 4;
	kan_tiles = NULL;
	kan_tiles_length1 = 0;
	_kan_tiles_size_ = 0;
	if (len > 0) {
		guint8* _tmp12_ = NULL;
		_tmp12_ = g_new0 (guint8, len);
		kan_tiles = (g_free (kan_tiles), NULL);
		kan_tiles = _tmp12_;
		kan_tiles_length1 = len;
		_kan_tiles_size_ = len;
		{
			gint j;
			j = 0;
			{
				gboolean _tmp13_;
				_tmp13_ = TRUE;
				while (TRUE) {
					if (!_tmp13_) {
						j++;
					}
					_tmp13_ = FALSE;
					if (!(j < len)) {
						break;
					}
					kan_tiles[j] = data[j + i];
				}
			}
		}
	}
	_tmp14_ = turn_action_new_set (action, discard_tile, late_kan_tile, late_kan_pon, kan_tiles, kan_tiles_length1);
	_tmp15_ = _tmp14_;
	turn_action_message_set_turn_action (self, _tmp15_);
	_turn_action_unref0 (_tmp15_);
	kan_tiles = (g_free (kan_tiles), NULL);
	_g_free0 (late_kan_pon);
	_g_free0 (late_kan_tile);
	_g_free0 (discard_tile);
	return self;
}


TurnActionMessage* turn_action_message_new (guint8* data, int data_length1) {
	return turn_action_message_construct (TYPE_TURN_ACTION_MESSAGE, data, data_length1);
}


TurnActionMessage* turn_action_message_construct_message (GType object_type, guint32 id, TurnAction* action) {
	TurnActionMessage * self = NULL;
	GArray* _tmp0_ = NULL;
	GArray* chunks;
	TurnActionTurnActionEnum _tmp1_;
	guint8 act;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	guint8 c;
	guint8* _tmp4_ = NULL;
	gint _tmp6_ = 0;
	guint8* _tmp7_ = NULL;
	guint8* _tmp8_ = NULL;
	gint _tmp10_ = 0;
	guint8* _tmp11_ = NULL;
	guint8* _tmp12_ = NULL;
	guint32 len;
	guint8* _tmp14_ = NULL;
	gint _tmp15_;
	gint _tmp18_;
	guint8* _tmp19_ = NULL;
	guint8* _tmp20_;
	gint _tmp20__length1;
	guint8* _tmp21_ = NULL;
	gint _tmp22_;
	g_return_val_if_fail (action != NULL, NULL);
	_tmp0_ = g_array_new (TRUE, TRUE, (gulong) 1);
	chunks = _tmp0_;
	_tmp1_ = turn_action_get_action (action);
	act = (guint8) _tmp1_;
	g_array_append_val (chunks, act);
	_tmp3_ = turn_action_get_discard_tile (action);
	if (_tmp3_ != NULL) {
		_tmp2_ = 1;
	} else {
		_tmp2_ = 0;
	}
	c = (guint8) _tmp2_;
	g_array_append_val (chunks, c);
	_tmp4_ = turn_action_get_discard_tile (action);
	if (_tmp4_ != NULL) {
		guint8* _tmp5_ = NULL;
		_tmp5_ = turn_action_get_discard_tile (action);
		g_array_append_val (chunks, *_tmp5_);
	}
	_tmp7_ = turn_action_get_late_kan_tile (action);
	if (_tmp7_ != NULL) {
		_tmp6_ = 1;
	} else {
		_tmp6_ = 0;
	}
	c = (guint8) _tmp6_;
	g_array_append_val (chunks, c);
	_tmp8_ = turn_action_get_late_kan_tile (action);
	if (_tmp8_ != NULL) {
		guint8* _tmp9_ = NULL;
		_tmp9_ = turn_action_get_late_kan_tile (action);
		g_array_append_val (chunks, *_tmp9_);
	}
	_tmp11_ = turn_action_get_late_kan_pon (action);
	if (_tmp11_ != NULL) {
		_tmp10_ = 1;
	} else {
		_tmp10_ = 0;
	}
	c = (guint8) _tmp10_;
	g_array_append_val (chunks, c);
	_tmp12_ = turn_action_get_late_kan_pon (action);
	if (_tmp12_ != NULL) {
		guint8* _tmp13_ = NULL;
		_tmp13_ = turn_action_get_late_kan_pon (action);
		g_array_append_val (chunks, *_tmp13_);
	}
	len = (guint32) 0;
	_tmp14_ = turn_action_get_kan_tiles (action, &_tmp15_);
	if (_tmp14_ != NULL) {
		guint8* _tmp16_ = NULL;
		gint _tmp17_;
		_tmp16_ = turn_action_get_kan_tiles (action, &_tmp17_);
		len = (guint32) _tmp17_;
	}
	_tmp19_ = int_to_data (len, &_tmp18_);
	_tmp20_ = _tmp19_;
	_tmp20__length1 = _tmp18_;
	g_array_append_vals (chunks, _tmp20_, (guint) 4);
	_tmp20_ = (g_free (_tmp20_), NULL);
	_tmp21_ = turn_action_get_kan_tiles (action, &_tmp22_);
	if (_tmp21_ != NULL) {
		guint8* _tmp23_ = NULL;
		gint _tmp24_;
		_tmp23_ = turn_action_get_kan_tiles (action, &_tmp24_);
		g_array_append_vals (chunks, _tmp23_, (guint) len);
	}
	self = (TurnActionMessage*) player_message_construct (object_type, chunks, PLAYER_MESSAGE_TURN_ACTION, id);
	turn_action_message_set_turn_action (self, action);
	_g_array_unref0 (chunks);
	return self;
}


TurnActionMessage* turn_action_message_new_message (guint32 id, TurnAction* action) {
	return turn_action_message_construct_message (TYPE_TURN_ACTION_MESSAGE, id, action);
}


TurnAction* turn_action_message_get_turn_action (TurnActionMessage* self) {
	TurnAction* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_turn_action;
	return result;
}


static gpointer _turn_action_ref0 (gpointer self) {
	return self ? turn_action_ref (self) : NULL;
}


static void turn_action_message_set_turn_action (TurnActionMessage* self, TurnAction* value) {
	TurnAction* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _turn_action_ref0 (value);
	_turn_action_unref0 (self->priv->_turn_action);
	self->priv->_turn_action = _tmp0_;
	g_object_notify ((GObject *) self, "turn-action");
}


static void turn_action_message_class_init (TurnActionMessageClass * klass) {
	turn_action_message_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TurnActionMessagePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_turn_action_message_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_turn_action_message_set_property;
	G_OBJECT_CLASS (klass)->finalize = turn_action_message_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TURN_ACTION_MESSAGE_TURN_ACTION, param_spec_turn_action ("turn-action", "turn-action", "turn-action", TYPE_TURN_ACTION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void turn_action_message_instance_init (TurnActionMessage * self) {
	self->priv = TURN_ACTION_MESSAGE_GET_PRIVATE (self);
}


static void turn_action_message_finalize (GObject* obj) {
	TurnActionMessage * self;
	self = TURN_ACTION_MESSAGE (obj);
	_turn_action_unref0 (self->priv->_turn_action);
	G_OBJECT_CLASS (turn_action_message_parent_class)->finalize (obj);
}


GType turn_action_message_get_type (void) {
	static volatile gsize turn_action_message_type_id__volatile = 0;
	if (g_once_init_enter (&turn_action_message_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TurnActionMessageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) turn_action_message_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TurnActionMessage), 0, (GInstanceInitFunc) turn_action_message_instance_init, NULL };
		GType turn_action_message_type_id;
		turn_action_message_type_id = g_type_register_static (TYPE_PLAYER_MESSAGE, "TurnActionMessage", &g_define_type_info, 0);
		g_once_init_leave (&turn_action_message_type_id__volatile, turn_action_message_type_id);
	}
	return turn_action_message_type_id__volatile;
}


static void _vala_turn_action_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TurnActionMessage * self;
	self = TURN_ACTION_MESSAGE (object);
	switch (property_id) {
		case TURN_ACTION_MESSAGE_TURN_ACTION:
		value_set_turn_action (value, turn_action_message_get_turn_action (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_turn_action_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TurnActionMessage * self;
	self = TURN_ACTION_MESSAGE (object);
	switch (property_id) {
		case TURN_ACTION_MESSAGE_TURN_ACTION:
		turn_action_message_set_turn_action (self, value_get_turn_action (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



