/* Stick.c generated by valac 0.16.1, the Vala compiler
 * generated from Stick.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <GL/glew.h>
#include <gobject/gvaluecollector.h>


#define TYPE_STICK (stick_get_type ())
#define STICK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STICK, Stick))
#define STICK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_STICK, StickClass))
#define IS_STICK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STICK))
#define IS_STICK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_STICK))
#define STICK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_STICK, StickClass))

typedef struct _Stick Stick;
typedef struct _StickClass StickClass;
typedef struct _StickPrivate StickPrivate;

#define TYPE_TEXTURE (texture_get_type ())
#define TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE, Texture))
#define TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE, TextureClass))
#define IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE))
#define IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE))
#define TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE, TextureClass))

typedef struct _Texture Texture;
typedef struct _TextureClass TextureClass;

#define TYPE_VECTOR (vector_get_type ())
#define VECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VECTOR, Vector))
#define VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VECTOR, VectorClass))
#define IS_VECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VECTOR))
#define IS_VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VECTOR))
#define VECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VECTOR, VectorClass))

typedef struct _Vector Vector;
typedef struct _VectorClass VectorClass;
#define _texture_unref0(var) ((var == NULL) ? NULL : (var = (texture_unref (var), NULL)))
#define _vector_unref0(var) ((var == NULL) ? NULL : (var = (vector_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecStick ParamSpecStick;

struct _Stick {
	GTypeInstance parent_instance;
	volatile int ref_count;
	StickPrivate * priv;
};

struct _StickClass {
	GTypeClass parent_class;
	void (*finalize) (Stick *self);
};

struct _StickPrivate {
	Texture* tile_texture;
	gint _points;
	Vector* _position;
	Vector* _rotation;
	gboolean _visible;
};

struct _ParamSpecStick {
	GParamSpec parent_instance;
};


static gpointer stick_parent_class = NULL;

gpointer stick_ref (gpointer instance);
void stick_unref (gpointer instance);
GParamSpec* param_spec_stick (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_stick (GValue* value, gpointer v_object);
void value_take_stick (GValue* value, gpointer v_object);
gpointer value_get_stick (const GValue* value);
GType stick_get_type (void) G_GNUC_CONST;
gpointer texture_ref (gpointer instance);
void texture_unref (gpointer instance);
GParamSpec* param_spec_texture (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_texture (GValue* value, gpointer v_object);
void value_take_texture (GValue* value, gpointer v_object);
gpointer value_get_texture (const GValue* value);
GType texture_get_type (void) G_GNUC_CONST;
gpointer vector_ref (gpointer instance);
void vector_unref (gpointer instance);
GParamSpec* param_spec_vector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_vector (GValue* value, gpointer v_object);
void value_take_vector (GValue* value, gpointer v_object);
gpointer value_get_vector (const GValue* value);
GType vector_get_type (void) G_GNUC_CONST;
#define STICK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_STICK, StickPrivate))
enum  {
	STICK_DUMMY_PROPERTY
};
#define STICK_SIZE 0.1f
#define STICK_size 0.25f
#define STICK_WIDTH (5.5f * STICK_size)
#define STICK_HEIGHT (0.5f * STICK_size)
#define STICK_LENGTH (0.3f * STICK_size)
Stick* stick_new (const gchar* name, gint points);
Stick* stick_construct (GType object_type, const gchar* name, gint points);
Texture* texture_load_texture (const gchar* name);
static void stick_set_points (Stick* self, gint value);
Vector* vector_new_empty (void);
Vector* vector_construct_empty (GType object_type);
void stick_set_position (Stick* self, Vector* value);
void stick_set_rotation (Stick* self, Vector* value);
void stick_render (Stick* self);
gboolean stick_get_visible (Stick* self);
Vector* stick_get_position (Stick* self);
gfloat vector_get_x (Vector* self);
gfloat vector_get_y (Vector* self);
gfloat vector_get_z (Vector* self);
Vector* stick_get_rotation (Stick* self);
static void stick_render_box (Stick* self);
static void stick_render_side (Stick* self, gfloat size);
static void stick_render_texture (Stick* self, gfloat size);
GLuint texture_get_texture (Texture* self);
gint stick_get_points (Stick* self);
void stick_set_visible (Stick* self, gboolean value);
static void stick_finalize (Stick* obj);


Stick* stick_construct (GType object_type, const gchar* name, gint points) {
	Stick* self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	Texture* _tmp3_ = NULL;
	gint _tmp4_;
	Vector* _tmp5_;
	Vector* _tmp6_;
	Vector* _tmp7_;
	Vector* _tmp8_;
#line 13 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 13 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self = (Stick*) g_type_create_instance (object_type);
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = name;
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = g_strconcat ("sticks/", _tmp0_, NULL);
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp2_ = _tmp1_;
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp3_ = texture_load_texture (_tmp2_);
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_texture_unref0 (self->priv->tile_texture);
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv->tile_texture = _tmp3_;
#line 15 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_g_free0 (_tmp2_);
#line 16 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp4_ = points;
#line 16 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_set_points (self, _tmp4_);
#line 17 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp5_ = vector_new_empty ();
#line 17 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp6_ = _tmp5_;
#line 17 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_set_position (self, _tmp6_);
#line 17 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (_tmp6_);
#line 18 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp7_ = vector_new_empty ();
#line 18 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp8_ = _tmp7_;
#line 18 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_set_rotation (self, _tmp8_);
#line 18 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (_tmp8_);
#line 13 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return self;
#line 182 "Stick.c"
}


Stick* stick_new (const gchar* name, gint points) {
#line 13 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return stick_construct (TYPE_STICK, name, points);
#line 189 "Stick.c"
}


void stick_render (Stick* self) {
	gboolean _tmp0_;
	Vector* _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	Vector* _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	Vector* _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	Vector* _tmp10_;
	gfloat _tmp11_;
	gfloat _tmp12_;
	Vector* _tmp13_;
	gfloat _tmp14_;
	gfloat _tmp15_;
	Vector* _tmp16_;
	gfloat _tmp17_;
	gfloat _tmp18_;
#line 22 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = self->priv->_visible;
#line 24 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (!_tmp0_) {
#line 25 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		return;
#line 221 "Stick.c"
	}
#line 27 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = self->priv->_position;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp2_ = vector_get_x (_tmp1_);
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp3_ = _tmp2_;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp4_ = self->priv->_position;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp5_ = vector_get_y (_tmp4_);
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp6_ = _tmp5_;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp7_ = self->priv->_position;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp8_ = vector_get_z (_tmp7_);
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp9_ = _tmp8_;
#line 29 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTranslatef ((GLfloat) _tmp3_, (GLfloat) _tmp6_, (GLfloat) _tmp9_);
#line 30 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp10_ = self->priv->_rotation;
#line 30 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp11_ = vector_get_x (_tmp10_);
#line 30 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp12_ = _tmp11_;
#line 30 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) (_tmp12_ / 1.0f), (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
#line 31 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp13_ = self->priv->_rotation;
#line 31 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp14_ = vector_get_y (_tmp13_);
#line 31 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp15_ = _tmp14_;
#line 31 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) (_tmp15_ / 1.0f), (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
#line 32 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp16_ = self->priv->_rotation;
#line 32 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp17_ = vector_get_z (_tmp16_);
#line 32 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp18_ = _tmp17_;
#line 32 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) (_tmp18_ / 1.0f), (GLfloat) 0, (GLfloat) 0, (GLfloat) 1);
#line 34 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTranslatef ((GLfloat) 0, ((GLfloat) STICK_HEIGHT) / 2, (GLfloat) 0);
#line 35 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glScalef ((GLfloat) STICK_WIDTH, (GLfloat) STICK_HEIGHT, (GLfloat) STICK_LENGTH);
#line 37 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glColor3f ((GLfloat) 1, (GLfloat) 1, (GLfloat) 1);
#line 38 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_box (self);
#line 40 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 279 "Stick.c"
}


static void stick_render_side (Stick* self, gfloat size) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	gfloat _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_;
	gfloat _tmp11_;
#line 43 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 45 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glBegin ((GLenum) GL_QUADS);
#line 46 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = size;
#line 46 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = size;
#line 46 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp2_ = size;
#line 46 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f (-((GLfloat) _tmp0_), -((GLfloat) _tmp1_), -((GLfloat) _tmp2_));
#line 47 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp3_ = size;
#line 47 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp4_ = size;
#line 47 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp5_ = size;
#line 47 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f (-((GLfloat) _tmp3_), (GLfloat) _tmp4_, -((GLfloat) _tmp5_));
#line 48 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp6_ = size;
#line 48 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp7_ = size;
#line 48 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp8_ = size;
#line 48 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f ((GLfloat) _tmp6_, (GLfloat) _tmp7_, -((GLfloat) _tmp8_));
#line 49 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp9_ = size;
#line 49 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp10_ = size;
#line 49 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp11_ = size;
#line 49 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f ((GLfloat) _tmp9_, -((GLfloat) _tmp10_), -((GLfloat) _tmp11_));
#line 50 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glEnd ();
#line 334 "Stick.c"
}


static void stick_render_texture (Stick* self, gfloat size) {
	gfloat _tmp0_;
	Texture* _tmp1_;
	GLuint _tmp2_;
	GLuint _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	gfloat _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_;
	gfloat _tmp11_;
#line 53 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = size;
#line 55 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTranslatef ((GLfloat) 0, (GLfloat) 0, (GLfloat) _tmp0_);
#line 57 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glEnable ((GLenum) GL_TEXTURE_2D);
#line 58 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = self->priv->tile_texture;
#line 58 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp2_ = texture_get_texture (_tmp1_);
#line 58 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp3_ = _tmp2_;
#line 58 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glBindTexture ((GLenum) GL_TEXTURE_2D, _tmp3_);
#line 60 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_S, GL_MIRRORED_REPEAT);
#line 61 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_T, GL_MIRRORED_REPEAT);
#line 63 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glBegin ((GLenum) GL_QUADS);
#line 65 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexCoord2f ((GLfloat) 0, (GLfloat) 1);
#line 66 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp4_ = size;
#line 66 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp5_ = size;
#line 66 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f (-((GLfloat) _tmp4_), -((GLfloat) _tmp5_), (GLfloat) 0);
#line 67 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexCoord2f ((GLfloat) 1, (GLfloat) 1);
#line 68 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp6_ = size;
#line 68 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp7_ = size;
#line 68 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f ((GLfloat) _tmp6_, -((GLfloat) _tmp7_), (GLfloat) 0);
#line 69 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexCoord2f ((GLfloat) 1, (GLfloat) 0);
#line 70 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp8_ = size;
#line 70 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp9_ = size;
#line 70 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f ((GLfloat) _tmp8_, (GLfloat) _tmp9_, (GLfloat) 0);
#line 71 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glTexCoord2f ((GLfloat) 0, (GLfloat) 0);
#line 72 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp10_ = size;
#line 72 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp11_ = size;
#line 72 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glVertex3f (-((GLfloat) _tmp10_), (GLfloat) _tmp11_, (GLfloat) 0);
#line 74 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glEnd ();
#line 77 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glDisable ((GLenum) GL_TEXTURE_2D);
#line 409 "Stick.c"
}


static void stick_render_box (Stick* self) {
#line 80 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 83 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 84 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_texture (self, STICK_size);
#line 85 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 88 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 89 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) 180, (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
#line 90 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_texture (self, STICK_size);
#line 91 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 94 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 95 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) 90, (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
#line 96 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_side (self, STICK_size);
#line 97 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 100 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 101 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) (-90), (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
#line 102 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_side (self, STICK_size);
#line 103 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 106 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 107 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) 90, (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
#line 108 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_side (self, STICK_size);
#line 109 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 112 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPushMatrix ();
#line 113 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glRotatef ((GLfloat) (-90), (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
#line 114 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_render_side (self, STICK_size);
#line 115 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	glPopMatrix ();
#line 462 "Stick.c"
}


gint stick_get_points (Stick* self) {
	gint result;
	gint _tmp0_;
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = self->priv->_points;
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	result = _tmp0_;
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return result;
#line 477 "Stick.c"
}


static void stick_set_points (Stick* self, gint value) {
	gint _tmp0_;
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = value;
#line 118 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv->_points = _tmp0_;
#line 489 "Stick.c"
}


Vector* stick_get_position (Stick* self) {
	Vector* result;
	Vector* _tmp0_;
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = self->priv->_position;
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	result = _tmp0_;
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return result;
#line 504 "Stick.c"
}


static gpointer _vector_ref0 (gpointer self) {
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return self ? vector_ref (self) : NULL;
#line 511 "Stick.c"
}


void stick_set_position (Stick* self, Vector* value) {
	Vector* _tmp0_;
	Vector* _tmp1_;
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = value;
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = _vector_ref0 (_tmp0_);
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (self->priv->_position);
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv->_position = _tmp1_;
#line 528 "Stick.c"
}


Vector* stick_get_rotation (Stick* self) {
	Vector* result;
	Vector* _tmp0_;
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = self->priv->_rotation;
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	result = _tmp0_;
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return result;
#line 543 "Stick.c"
}


void stick_set_rotation (Stick* self, Vector* value) {
	Vector* _tmp0_;
	Vector* _tmp1_;
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = value;
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp1_ = _vector_ref0 (_tmp0_);
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (self->priv->_rotation);
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv->_rotation = _tmp1_;
#line 560 "Stick.c"
}


gboolean stick_get_visible (Stick* self) {
	gboolean result;
	gboolean _tmp0_;
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = self->priv->_visible;
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	result = _tmp0_;
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return result;
#line 575 "Stick.c"
}


void stick_set_visible (Stick* self, gboolean value) {
	gboolean _tmp0_;
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (self != NULL);
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_tmp0_ = value;
#line 121 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv->_visible = _tmp0_;
#line 587 "Stick.c"
}


static void value_stick_init (GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	value->data[0].v_pointer = NULL;
#line 594 "Stick.c"
}


static void value_stick_free_value (GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		stick_unref (value->data[0].v_pointer);
#line 603 "Stick.c"
	}
}


static void value_stick_copy_value (const GValue* src_value, GValue* dest_value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (src_value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		dest_value->data[0].v_pointer = stick_ref (src_value->data[0].v_pointer);
#line 613 "Stick.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		dest_value->data[0].v_pointer = NULL;
#line 617 "Stick.c"
	}
}


static gpointer value_stick_peek_pointer (const GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return value->data[0].v_pointer;
#line 625 "Stick.c"
}


static gchar* value_stick_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (collect_values[0].v_pointer) {
#line 632 "Stick.c"
		Stick* object;
		object = collect_values[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		if (object->parent_instance.g_class == NULL) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 639 "Stick.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 643 "Stick.c"
		}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = stick_ref (object);
#line 647 "Stick.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = NULL;
#line 651 "Stick.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return NULL;
#line 655 "Stick.c"
}


static gchar* value_stick_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Stick** object_p;
	object_p = collect_values[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (!object_p) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 666 "Stick.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (!value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		*object_p = NULL;
#line 672 "Stick.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		*object_p = value->data[0].v_pointer;
#line 676 "Stick.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		*object_p = stick_ref (value->data[0].v_pointer);
#line 680 "Stick.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return NULL;
#line 684 "Stick.c"
}


GParamSpec* param_spec_stick (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecStick* spec;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_STICK), NULL);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return G_PARAM_SPEC (spec);
#line 698 "Stick.c"
}


gpointer value_get_stick (const GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK), NULL);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return value->data[0].v_pointer;
#line 707 "Stick.c"
}


void value_set_stick (GValue* value, gpointer v_object) {
	Stick* old;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (v_object) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STICK));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = v_object;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		stick_ref (value->data[0].v_pointer);
#line 727 "Stick.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = NULL;
#line 731 "Stick.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (old) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		stick_unref (old);
#line 737 "Stick.c"
	}
}


void value_take_stick (GValue* value, gpointer v_object) {
	Stick* old;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (v_object) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STICK));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = v_object;
#line 756 "Stick.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		value->data[0].v_pointer = NULL;
#line 760 "Stick.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (old) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		stick_unref (old);
#line 766 "Stick.c"
	}
}


static void stick_class_init (StickClass * klass) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	stick_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	STICK_CLASS (klass)->finalize = stick_finalize;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_type_class_add_private (klass, sizeof (StickPrivate));
#line 778 "Stick.c"
}


static void stick_instance_init (Stick * self) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->priv = STICK_GET_PRIVATE (self);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self->ref_count = 1;
#line 787 "Stick.c"
}


static void stick_finalize (Stick* obj) {
	Stick * self;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	self = STICK (obj);
#line 11 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_texture_unref0 (self->priv->tile_texture);
#line 119 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (self->priv->_position);
#line 120 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	_vector_unref0 (self->priv->_rotation);
#line 801 "Stick.c"
}


GType stick_get_type (void) {
	static volatile gsize stick_type_id__volatile = 0;
	if (g_once_init_enter (&stick_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_stick_init, value_stick_free_value, value_stick_copy_value, value_stick_peek_pointer, "p", value_stick_collect_value, "p", value_stick_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (StickClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stick_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Stick), 0, (GInstanceInitFunc) stick_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType stick_type_id;
		stick_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Stick", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&stick_type_id__volatile, stick_type_id);
	}
	return stick_type_id__volatile;
}


gpointer stick_ref (gpointer instance) {
	Stick* self;
	self = instance;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	g_atomic_int_inc (&self->ref_count);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	return instance;
#line 826 "Stick.c"
}


void stick_unref (gpointer instance) {
	Stick* self;
	self = instance;
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		STICK_GET_CLASS (self)->finalize (self);
#line 3 "/home/fluffy/RiichiMahjong/source/Game/Stick.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 839 "Stick.c"
	}
}



