/* Stick.c generated by valac 0.12.0, the Vala compiler
 * generated from Stick.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <GL/glew.h>
#include <gobject/gvaluecollector.h>


#define TYPE_STICK (stick_get_type ())
#define STICK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STICK, Stick))
#define STICK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_STICK, StickClass))
#define IS_STICK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STICK))
#define IS_STICK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_STICK))
#define STICK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_STICK, StickClass))

typedef struct _Stick Stick;
typedef struct _StickClass StickClass;
typedef struct _StickPrivate StickPrivate;

#define TYPE_TEXTURE (texture_get_type ())
#define TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE, Texture))
#define TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE, TextureClass))
#define IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE))
#define IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE))
#define TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE, TextureClass))

typedef struct _Texture Texture;
typedef struct _TextureClass TextureClass;

#define TYPE_VECTOR (vector_get_type ())
#define VECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VECTOR, Vector))
#define VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VECTOR, VectorClass))
#define IS_VECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VECTOR))
#define IS_VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VECTOR))
#define VECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VECTOR, VectorClass))

typedef struct _Vector Vector;
typedef struct _VectorClass VectorClass;
#define _texture_unref0(var) ((var == NULL) ? NULL : (var = (texture_unref (var), NULL)))
#define _vector_unref0(var) ((var == NULL) ? NULL : (var = (vector_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecStick ParamSpecStick;

struct _Stick {
	GTypeInstance parent_instance;
	volatile int ref_count;
	StickPrivate * priv;
};

struct _StickClass {
	GTypeClass parent_class;
	void (*finalize) (Stick *self);
};

struct _StickPrivate {
	Texture* tile_texture;
	gint _points;
	Vector* _position;
	Vector* _rotation;
	gboolean _visible;
};

struct _ParamSpecStick {
	GParamSpec parent_instance;
};


static gpointer stick_parent_class = NULL;

gpointer stick_ref (gpointer instance);
void stick_unref (gpointer instance);
GParamSpec* param_spec_stick (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_stick (GValue* value, gpointer v_object);
void value_take_stick (GValue* value, gpointer v_object);
gpointer value_get_stick (const GValue* value);
GType stick_get_type (void) G_GNUC_CONST;
gpointer texture_ref (gpointer instance);
void texture_unref (gpointer instance);
GParamSpec* param_spec_texture (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_texture (GValue* value, gpointer v_object);
void value_take_texture (GValue* value, gpointer v_object);
gpointer value_get_texture (const GValue* value);
GType texture_get_type (void) G_GNUC_CONST;
gpointer vector_ref (gpointer instance);
void vector_unref (gpointer instance);
GParamSpec* param_spec_vector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_vector (GValue* value, gpointer v_object);
void value_take_vector (GValue* value, gpointer v_object);
gpointer value_get_vector (const GValue* value);
GType vector_get_type (void) G_GNUC_CONST;
#define STICK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_STICK, StickPrivate))
enum  {
	STICK_DUMMY_PROPERTY
};
#define STICK_SIZE 0.1f
#define STICK_size 0.25f
#define STICK_WIDTH (5.5f * STICK_size)
#define STICK_HEIGHT (0.5f * STICK_size)
#define STICK_LENGTH (0.3f * STICK_size)
Stick* stick_new (const gchar* name, gint points);
Stick* stick_construct (GType object_type, const gchar* name, gint points);
Texture* texture_load_texture (const gchar* name);
static void stick_set_points (Stick* self, gint value);
Vector* vector_new_empty (void);
Vector* vector_construct_empty (GType object_type);
void stick_set_position (Stick* self, Vector* value);
void stick_set_rotation (Stick* self, Vector* value);
void stick_render (Stick* self);
gboolean stick_get_visible (Stick* self);
Vector* stick_get_position (Stick* self);
gfloat vector_get_x (Vector* self);
gfloat vector_get_y (Vector* self);
gfloat vector_get_z (Vector* self);
Vector* stick_get_rotation (Stick* self);
static void stick_render_box (Stick* self);
static void stick_render_side (Stick* self, gfloat size);
static void stick_render_texture (Stick* self, gfloat size);
GLuint texture_get_texture (Texture* self);
gint stick_get_points (Stick* self);
void stick_set_visible (Stick* self, gboolean value);
static void stick_finalize (Stick* obj);


Stick* stick_construct (GType object_type, const gchar* name, gint points) {
	Stick* self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	Texture* _tmp2_ = NULL;
	Vector* _tmp3_ = NULL;
	Vector* _tmp4_;
	Vector* _tmp5_ = NULL;
	Vector* _tmp6_;
	g_return_val_if_fail (name != NULL, NULL);
	self = (Stick*) g_type_create_instance (object_type);
	_tmp0_ = g_strconcat ("sticks/", name, NULL);
	_tmp1_ = _tmp0_;
	_tmp2_ = texture_load_texture (_tmp1_);
	_texture_unref0 (self->priv->tile_texture);
	self->priv->tile_texture = _tmp2_;
	_g_free0 (_tmp1_);
	stick_set_points (self, points);
	_tmp3_ = vector_new_empty ();
	_tmp4_ = _tmp3_;
	stick_set_position (self, _tmp4_);
	_vector_unref0 (_tmp4_);
	_tmp5_ = vector_new_empty ();
	_tmp6_ = _tmp5_;
	stick_set_rotation (self, _tmp6_);
	_vector_unref0 (_tmp6_);
	return self;
}


Stick* stick_new (const gchar* name, gint points) {
	return stick_construct (TYPE_STICK, name, points);
}


void stick_render (Stick* self) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	g_return_if_fail (self != NULL);
	if (!self->priv->_visible) {
		return;
	}
	glPushMatrix ();
	_tmp0_ = vector_get_x (self->priv->_position);
	_tmp1_ = vector_get_y (self->priv->_position);
	_tmp2_ = vector_get_z (self->priv->_position);
	glTranslatef ((GLfloat) _tmp0_, (GLfloat) _tmp1_, (GLfloat) _tmp2_);
	_tmp3_ = vector_get_x (self->priv->_rotation);
	glRotatef ((GLfloat) (_tmp3_ / 1.0f), (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
	_tmp4_ = vector_get_y (self->priv->_rotation);
	glRotatef ((GLfloat) (_tmp4_ / 1.0f), (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
	_tmp5_ = vector_get_z (self->priv->_rotation);
	glRotatef ((GLfloat) (_tmp5_ / 1.0f), (GLfloat) 0, (GLfloat) 0, (GLfloat) 1);
	glTranslatef ((GLfloat) 0, ((GLfloat) STICK_HEIGHT) / 2, (GLfloat) 0);
	glScalef ((GLfloat) STICK_WIDTH, (GLfloat) STICK_HEIGHT, (GLfloat) STICK_LENGTH);
	glColor3f ((GLfloat) 1, (GLfloat) 1, (GLfloat) 1);
	stick_render_box (self);
	glPopMatrix ();
}


static void stick_render_side (Stick* self, gfloat size) {
	g_return_if_fail (self != NULL);
	glBegin ((GLenum) GL_QUADS);
	glVertex3f (-((GLfloat) size), -((GLfloat) size), -((GLfloat) size));
	glVertex3f (-((GLfloat) size), (GLfloat) size, -((GLfloat) size));
	glVertex3f ((GLfloat) size, (GLfloat) size, -((GLfloat) size));
	glVertex3f ((GLfloat) size, -((GLfloat) size), -((GLfloat) size));
	glEnd ();
}


static void stick_render_texture (Stick* self, gfloat size) {
	GLuint _tmp0_;
	g_return_if_fail (self != NULL);
	glTranslatef ((GLfloat) 0, (GLfloat) 0, (GLfloat) size);
	glEnable ((GLenum) GL_TEXTURE_2D);
	_tmp0_ = texture_get_texture (self->priv->tile_texture);
	glBindTexture ((GLenum) GL_TEXTURE_2D, _tmp0_);
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_S, GL_MIRRORED_REPEAT);
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_T, GL_MIRRORED_REPEAT);
	glBegin ((GLenum) GL_QUADS);
	glTexCoord2f ((GLfloat) 0, (GLfloat) 1);
	glVertex3f (-((GLfloat) size), -((GLfloat) size), (GLfloat) 0);
	glTexCoord2f ((GLfloat) 1, (GLfloat) 1);
	glVertex3f ((GLfloat) size, -((GLfloat) size), (GLfloat) 0);
	glTexCoord2f ((GLfloat) 1, (GLfloat) 0);
	glVertex3f ((GLfloat) size, (GLfloat) size, (GLfloat) 0);
	glTexCoord2f ((GLfloat) 0, (GLfloat) 0);
	glVertex3f (-((GLfloat) size), (GLfloat) size, (GLfloat) 0);
	glEnd ();
	glDisable ((GLenum) GL_TEXTURE_2D);
}


static void stick_render_box (Stick* self) {
	g_return_if_fail (self != NULL);
	glPushMatrix ();
	stick_render_texture (self, STICK_size);
	glPopMatrix ();
	glPushMatrix ();
	glRotatef ((GLfloat) 180, (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
	stick_render_texture (self, STICK_size);
	glPopMatrix ();
	glPushMatrix ();
	glRotatef ((GLfloat) 90, (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
	stick_render_side (self, STICK_size);
	glPopMatrix ();
	glPushMatrix ();
	glRotatef ((GLfloat) (-90), (GLfloat) 1, (GLfloat) 0, (GLfloat) 0);
	stick_render_side (self, STICK_size);
	glPopMatrix ();
	glPushMatrix ();
	glRotatef ((GLfloat) 90, (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
	stick_render_side (self, STICK_size);
	glPopMatrix ();
	glPushMatrix ();
	glRotatef ((GLfloat) (-90), (GLfloat) 0, (GLfloat) 1, (GLfloat) 0);
	stick_render_side (self, STICK_size);
	glPopMatrix ();
}


gint stick_get_points (Stick* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_points;
	return result;
}


static void stick_set_points (Stick* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_points = value;
}


Vector* stick_get_position (Stick* self) {
	Vector* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_position;
	return result;
}


static gpointer _vector_ref0 (gpointer self) {
	return self ? vector_ref (self) : NULL;
}


void stick_set_position (Stick* self, Vector* value) {
	Vector* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vector_ref0 (value);
	_vector_unref0 (self->priv->_position);
	self->priv->_position = _tmp0_;
}


Vector* stick_get_rotation (Stick* self) {
	Vector* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_rotation;
	return result;
}


void stick_set_rotation (Stick* self, Vector* value) {
	Vector* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vector_ref0 (value);
	_vector_unref0 (self->priv->_rotation);
	self->priv->_rotation = _tmp0_;
}


gboolean stick_get_visible (Stick* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_visible;
	return result;
}


void stick_set_visible (Stick* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_visible = value;
}


static void value_stick_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_stick_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		stick_unref (value->data[0].v_pointer);
	}
}


static void value_stick_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = stick_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_stick_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_stick_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Stick* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = stick_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_stick_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Stick** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = stick_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_stick (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecStick* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_STICK), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_stick (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK), NULL);
	return value->data[0].v_pointer;
}


void value_set_stick (GValue* value, gpointer v_object) {
	Stick* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STICK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		stick_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stick_unref (old);
	}
}


void value_take_stick (GValue* value, gpointer v_object) {
	Stick* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_STICK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_STICK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stick_unref (old);
	}
}


static void stick_class_init (StickClass * klass) {
	stick_parent_class = g_type_class_peek_parent (klass);
	STICK_CLASS (klass)->finalize = stick_finalize;
	g_type_class_add_private (klass, sizeof (StickPrivate));
}


static void stick_instance_init (Stick * self) {
	self->priv = STICK_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void stick_finalize (Stick* obj) {
	Stick * self;
	self = STICK (obj);
	_texture_unref0 (self->priv->tile_texture);
	_vector_unref0 (self->priv->_position);
	_vector_unref0 (self->priv->_rotation);
}


GType stick_get_type (void) {
	static volatile gsize stick_type_id__volatile = 0;
	if (g_once_init_enter (&stick_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_stick_init, value_stick_free_value, value_stick_copy_value, value_stick_peek_pointer, "p", value_stick_collect_value, "p", value_stick_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (StickClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stick_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Stick), 0, (GInstanceInitFunc) stick_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType stick_type_id;
		stick_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Stick", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&stick_type_id__volatile, stick_type_id);
	}
	return stick_type_id__volatile;
}


gpointer stick_ref (gpointer instance) {
	Stick* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void stick_unref (gpointer instance) {
	Stick* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		STICK_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



