/* Yaku.c generated by valac 0.12.0, the Vala compiler
 * generated from Yaku.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define TYPE_YAKU (yaku_get_type ())
#define YAKU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_YAKU, Yaku))
#define YAKU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_YAKU, YakuClass))
#define IS_YAKU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_YAKU))
#define IS_YAKU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_YAKU))
#define YAKU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_YAKU, YakuClass))

typedef struct _Yaku Yaku;
typedef struct _YakuClass YakuClass;
typedef struct _YakuPrivate YakuPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_TILE (tile_get_type ())
#define TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILE, Tile))
#define TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILE, TileClass))
#define IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILE))
#define IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILE))
#define TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILE, TileClass))

typedef struct _Tile Tile;
typedef struct _TileClass TileClass;

#define TYPE_CALL (call_get_type ())
#define CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CALL, Call))
#define CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CALL, CallClass))
#define IS_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CALL))
#define IS_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CALL))
#define CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CALL, CallClass))

typedef struct _Call Call;
typedef struct _CallClass CallClass;

#define TYPE_TILE_TYPE (tile_type_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _call_unref0(var) ((var == NULL) ? NULL : (var = (call_unref (var), NULL)))
typedef struct _ParamSpecYaku ParamSpecYaku;

struct _Yaku {
	GTypeInstance parent_instance;
	volatile int ref_count;
	YakuPrivate * priv;
};

struct _YakuClass {
	GTypeClass parent_class;
	void (*finalize) (Yaku *self);
};

struct _YakuPrivate {
	gint _han;
	gchar* _name;
};

typedef enum  {
	TILE_TYPE_MAN1 = 0,
	TILE_TYPE_MAN2,
	TILE_TYPE_MAN3,
	TILE_TYPE_MAN4,
	TILE_TYPE_MAN5,
	TILE_TYPE_MAN6,
	TILE_TYPE_MAN7,
	TILE_TYPE_MAN8,
	TILE_TYPE_MAN9,
	TILE_TYPE_PIN1,
	TILE_TYPE_PIN2,
	TILE_TYPE_PIN3,
	TILE_TYPE_PIN4,
	TILE_TYPE_PIN5,
	TILE_TYPE_PIN6,
	TILE_TYPE_PIN7,
	TILE_TYPE_PIN8,
	TILE_TYPE_PIN9,
	TILE_TYPE_SOU1,
	TILE_TYPE_SOU2,
	TILE_TYPE_SOU3,
	TILE_TYPE_SOU4,
	TILE_TYPE_SOU5,
	TILE_TYPE_SOU6,
	TILE_TYPE_SOU7,
	TILE_TYPE_SOU8,
	TILE_TYPE_SOU9,
	TILE_TYPE_HIGASHI,
	TILE_TYPE_MINAMI,
	TILE_TYPE_NISHI,
	TILE_TYPE_KITA,
	TILE_TYPE_HATSU,
	TILE_TYPE_HAKU,
	TILE_TYPE_CHUN
} TILE_TYPE;

struct _ParamSpecYaku {
	GParamSpec parent_instance;
};


static gpointer yaku_parent_class = NULL;

gpointer yaku_ref (gpointer instance);
void yaku_unref (gpointer instance);
GParamSpec* param_spec_yaku (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_yaku (GValue* value, gpointer v_object);
void value_take_yaku (GValue* value, gpointer v_object);
gpointer value_get_yaku (const GValue* value);
GType yaku_get_type (void) G_GNUC_CONST;
#define YAKU_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_YAKU, YakuPrivate))
enum  {
	YAKU_DUMMY_PROPERTY
};
static Yaku* yaku_new_make_riichi (void);
static Yaku* yaku_construct_make_riichi (GType object_type);
static void yaku_set_han (Yaku* self, gint value);
static void yaku_set_name (Yaku* self, const gchar* value);
static Yaku* yaku_new_make_double_riichi (void);
static Yaku* yaku_construct_make_double_riichi (GType object_type);
static Yaku* yaku_new_make_tsumo (void);
static Yaku* yaku_construct_make_tsumo (GType object_type);
static Yaku* yaku_new_make_tan_yao (void);
static Yaku* yaku_construct_make_tan_yao (GType object_type);
Yaku* yaku_riichi (gint turn);
Yaku* yaku_tsumo (gboolean open);
GType tile_get_type (void) G_GNUC_CONST;
gpointer call_ref (gpointer instance);
void call_unref (gpointer instance);
GParamSpec* param_spec_call (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_call (GValue* value, gpointer v_object);
void value_take_call (GValue* value, gpointer v_object);
gpointer value_get_call (const GValue* value);
GType call_get_type (void) G_GNUC_CONST;
Yaku* yaku_tan_yao (GeeArrayList* hand, GeeArrayList* calls);
gint tile_get_tile_type (Tile* self);
GType tile_type_get_type (void) G_GNUC_CONST;
Tile** call_get_tiles (Call* self, int* result_length1);
Yaku* yaku_new (void);
Yaku* yaku_construct (GType object_type);
gint yaku_get_han (Yaku* self);
const gchar* yaku_get_name (Yaku* self);
static void yaku_finalize (Yaku* obj);


static Yaku* yaku_construct_make_riichi (GType object_type) {
	Yaku* self = NULL;
	self = (Yaku*) g_type_create_instance (object_type);
	yaku_set_han (self, 1);
	yaku_set_name (self, "Riichi");
	return self;
}


static Yaku* yaku_new_make_riichi (void) {
	return yaku_construct_make_riichi (TYPE_YAKU);
}


static Yaku* yaku_construct_make_double_riichi (GType object_type) {
	Yaku* self = NULL;
	self = (Yaku*) g_type_create_instance (object_type);
	yaku_set_han (self, 2);
	yaku_set_name (self, "Double Riichi");
	return self;
}


static Yaku* yaku_new_make_double_riichi (void) {
	return yaku_construct_make_double_riichi (TYPE_YAKU);
}


static Yaku* yaku_construct_make_tsumo (GType object_type) {
	Yaku* self = NULL;
	self = (Yaku*) g_type_create_instance (object_type);
	yaku_set_han (self, 1);
	yaku_set_name (self, "Tsumo");
	return self;
}


static Yaku* yaku_new_make_tsumo (void) {
	return yaku_construct_make_tsumo (TYPE_YAKU);
}


static Yaku* yaku_construct_make_tan_yao (GType object_type) {
	Yaku* self = NULL;
	self = (Yaku*) g_type_create_instance (object_type);
	yaku_set_han (self, 2);
	yaku_set_name (self, "Tan-Yao");
	return self;
}


static Yaku* yaku_new_make_tan_yao (void) {
	return yaku_construct_make_tan_yao (TYPE_YAKU);
}


Yaku* yaku_riichi (gint turn) {
	Yaku* result = NULL;
	if (turn == (-1)) {
		result = NULL;
		return result;
	} else {
		if (turn == 1) {
			Yaku* _tmp0_ = NULL;
			_tmp0_ = yaku_new_make_double_riichi ();
			result = _tmp0_;
			return result;
		} else {
			Yaku* _tmp1_ = NULL;
			_tmp1_ = yaku_new_make_riichi ();
			result = _tmp1_;
			return result;
		}
	}
}


Yaku* yaku_tsumo (gboolean open) {
	Yaku* result = NULL;
	Yaku* _tmp0_ = NULL;
	if (open) {
		result = NULL;
		return result;
	}
	_tmp0_ = yaku_new_make_tsumo ();
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


Yaku* yaku_tan_yao (GeeArrayList* hand, GeeArrayList* calls) {
	Yaku* result = NULL;
	Yaku* _tmp31_ = NULL;
	g_return_val_if_fail (hand != NULL, NULL);
	g_return_val_if_fail (calls != NULL, NULL);
	{
		GeeArrayList* _tmp0_;
		GeeArrayList* _tile_list;
		gint _tmp1_;
		gint _tile_size;
		gint _tile_index;
		_tmp0_ = _g_object_ref0 (hand);
		_tile_list = _tmp0_;
		_tmp1_ = gee_collection_get_size ((GeeCollection*) _tile_list);
		_tile_size = _tmp1_;
		_tile_index = -1;
		while (TRUE) {
			gpointer _tmp2_ = NULL;
			Tile* tile;
			gboolean _tmp3_ = FALSE;
			gboolean _tmp4_ = FALSE;
			gboolean _tmp5_ = FALSE;
			gboolean _tmp6_ = FALSE;
			gboolean _tmp7_ = FALSE;
			gint _tmp8_;
			_tile_index = _tile_index + 1;
			if (!(_tile_index < _tile_size)) {
				break;
			}
			_tmp2_ = gee_abstract_list_get ((GeeAbstractList*) _tile_list, _tile_index);
			tile = (Tile*) _tmp2_;
			_tmp8_ = tile_get_tile_type (tile);
			if (_tmp8_ <= TILE_TYPE_MAN1) {
				_tmp7_ = TRUE;
			} else {
				gint _tmp9_;
				_tmp9_ = tile_get_tile_type (tile);
				_tmp7_ = _tmp9_ == TILE_TYPE_MAN9;
			}
			if (_tmp7_) {
				_tmp6_ = TRUE;
			} else {
				gint _tmp10_;
				_tmp10_ = tile_get_tile_type (tile);
				_tmp6_ = _tmp10_ == TILE_TYPE_PIN1;
			}
			if (_tmp6_) {
				_tmp5_ = TRUE;
			} else {
				gint _tmp11_;
				_tmp11_ = tile_get_tile_type (tile);
				_tmp5_ = _tmp11_ == TILE_TYPE_PIN9;
			}
			if (_tmp5_) {
				_tmp4_ = TRUE;
			} else {
				gint _tmp12_;
				_tmp12_ = tile_get_tile_type (tile);
				_tmp4_ = _tmp12_ == TILE_TYPE_SOU1;
			}
			if (_tmp4_) {
				_tmp3_ = TRUE;
			} else {
				gint _tmp13_;
				_tmp13_ = tile_get_tile_type (tile);
				_tmp3_ = _tmp13_ >= TILE_TYPE_SOU9;
			}
			if (_tmp3_) {
				result = NULL;
				_g_object_unref0 (tile);
				_g_object_unref0 (_tile_list);
				return result;
			}
			_g_object_unref0 (tile);
		}
		_g_object_unref0 (_tile_list);
	}
	{
		GeeArrayList* _tmp14_;
		GeeArrayList* _call_list;
		gint _tmp15_;
		gint _call_size;
		gint _call_index;
		_tmp14_ = _g_object_ref0 (calls);
		_call_list = _tmp14_;
		_tmp15_ = gee_collection_get_size ((GeeCollection*) _call_list);
		_call_size = _tmp15_;
		_call_index = -1;
		while (TRUE) {
			gpointer _tmp16_ = NULL;
			Call* call;
			Tile** _tmp17_ = NULL;
			gint _tmp18_;
			_call_index = _call_index + 1;
			if (!(_call_index < _call_size)) {
				break;
			}
			_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _call_list, _call_index);
			call = (Call*) _tmp16_;
			_tmp17_ = call_get_tiles (call, &_tmp18_);
			{
				Tile** tile_collection;
				int tile_collection_length1;
				int tile_it;
				tile_collection = _tmp17_;
				tile_collection_length1 = _tmp18_;
				for (tile_it = 0; tile_it < _tmp18_; tile_it = tile_it + 1) {
					Tile* _tmp19_;
					Tile* tile;
					_tmp19_ = _g_object_ref0 (tile_collection[tile_it]);
					tile = _tmp19_;
					{
						gboolean _tmp20_ = FALSE;
						gboolean _tmp21_ = FALSE;
						gboolean _tmp22_ = FALSE;
						gboolean _tmp23_ = FALSE;
						gboolean _tmp24_ = FALSE;
						gint _tmp25_;
						_tmp25_ = tile_get_tile_type (tile);
						if (_tmp25_ <= TILE_TYPE_MAN1) {
							_tmp24_ = TRUE;
						} else {
							gint _tmp26_;
							_tmp26_ = tile_get_tile_type (tile);
							_tmp24_ = _tmp26_ == TILE_TYPE_MAN9;
						}
						if (_tmp24_) {
							_tmp23_ = TRUE;
						} else {
							gint _tmp27_;
							_tmp27_ = tile_get_tile_type (tile);
							_tmp23_ = _tmp27_ == TILE_TYPE_PIN1;
						}
						if (_tmp23_) {
							_tmp22_ = TRUE;
						} else {
							gint _tmp28_;
							_tmp28_ = tile_get_tile_type (tile);
							_tmp22_ = _tmp28_ == TILE_TYPE_PIN9;
						}
						if (_tmp22_) {
							_tmp21_ = TRUE;
						} else {
							gint _tmp29_;
							_tmp29_ = tile_get_tile_type (tile);
							_tmp21_ = _tmp29_ == TILE_TYPE_SOU1;
						}
						if (_tmp21_) {
							_tmp20_ = TRUE;
						} else {
							gint _tmp30_;
							_tmp30_ = tile_get_tile_type (tile);
							_tmp20_ = _tmp30_ >= TILE_TYPE_SOU9;
						}
						if (_tmp20_) {
							result = NULL;
							_g_object_unref0 (tile);
							_call_unref0 (call);
							_g_object_unref0 (_call_list);
							return result;
						}
						_g_object_unref0 (tile);
					}
				}
			}
			_call_unref0 (call);
		}
		_g_object_unref0 (_call_list);
	}
	_tmp31_ = yaku_new_make_tan_yao ();
	result = _tmp31_;
	return result;
}


Yaku* yaku_construct (GType object_type) {
	Yaku* self = NULL;
	self = (Yaku*) g_type_create_instance (object_type);
	return self;
}


Yaku* yaku_new (void) {
	return yaku_construct (TYPE_YAKU);
}


gint yaku_get_han (Yaku* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_han;
	return result;
}


static void yaku_set_han (Yaku* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_han = value;
}


const gchar* yaku_get_name (Yaku* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


static void yaku_set_name (Yaku* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp0_;
}


static void value_yaku_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_yaku_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		yaku_unref (value->data[0].v_pointer);
	}
}


static void value_yaku_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = yaku_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_yaku_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_yaku_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Yaku* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = yaku_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_yaku_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Yaku** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = yaku_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_yaku (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecYaku* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_YAKU), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_yaku (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_YAKU), NULL);
	return value->data[0].v_pointer;
}


void value_set_yaku (GValue* value, gpointer v_object) {
	Yaku* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_YAKU));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_YAKU));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		yaku_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yaku_unref (old);
	}
}


void value_take_yaku (GValue* value, gpointer v_object) {
	Yaku* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_YAKU));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_YAKU));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yaku_unref (old);
	}
}


static void yaku_class_init (YakuClass * klass) {
	yaku_parent_class = g_type_class_peek_parent (klass);
	YAKU_CLASS (klass)->finalize = yaku_finalize;
	g_type_class_add_private (klass, sizeof (YakuPrivate));
}


static void yaku_instance_init (Yaku * self) {
	self->priv = YAKU_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void yaku_finalize (Yaku* obj) {
	Yaku * self;
	self = YAKU (obj);
	_g_free0 (self->priv->_name);
}


GType yaku_get_type (void) {
	static volatile gsize yaku_type_id__volatile = 0;
	if (g_once_init_enter (&yaku_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_yaku_init, value_yaku_free_value, value_yaku_copy_value, value_yaku_peek_pointer, "p", value_yaku_collect_value, "p", value_yaku_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (YakuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yaku_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Yaku), 0, (GInstanceInitFunc) yaku_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType yaku_type_id;
		yaku_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Yaku", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&yaku_type_id__volatile, yaku_type_id);
	}
	return yaku_type_id__volatile;
}


gpointer yaku_ref (gpointer instance) {
	Yaku* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void yaku_unref (gpointer instance) {
	Yaku* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		YAKU_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



