/* MainMenu.c generated by valac 0.12.0, the Vala compiler
 * generated from MainMenu.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gee.h>


#define TYPE_VIEW (view_get_type ())
#define VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VIEW, View))
#define VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VIEW, ViewClass))
#define IS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VIEW))
#define IS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VIEW))
#define VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VIEW, ViewClass))

typedef struct _View View;
typedef struct _ViewClass ViewClass;
typedef struct _ViewPrivate ViewPrivate;

#define TYPE_IRESOURCE_STORE (iresource_store_get_type ())
#define IRESOURCE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IRESOURCE_STORE, IResourceStore))
#define IS_IRESOURCE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IRESOURCE_STORE))
#define IRESOURCE_STORE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_IRESOURCE_STORE, IResourceStoreIface))

typedef struct _IResourceStore IResourceStore;
typedef struct _IResourceStoreIface IResourceStoreIface;

#define TYPE_RENDER3_DOBJECT (render3_dobject_get_type ())
#define RENDER3_DOBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER3_DOBJECT, Render3DObject))
#define RENDER3_DOBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER3_DOBJECT, Render3DObjectClass))
#define IS_RENDER3_DOBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER3_DOBJECT))
#define IS_RENDER3_DOBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER3_DOBJECT))
#define RENDER3_DOBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER3_DOBJECT, Render3DObjectClass))

typedef struct _Render3DObject Render3DObject;
typedef struct _Render3DObjectClass Render3DObjectClass;

#define TYPE_RENDER_STATE (render_state_get_type ())
#define RENDER_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER_STATE, RenderState))
#define RENDER_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER_STATE, RenderStateClass))
#define IS_RENDER_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER_STATE))
#define IS_RENDER_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER_STATE))
#define RENDER_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER_STATE, RenderStateClass))

typedef struct _RenderState RenderState;
typedef struct _RenderStateClass RenderStateClass;

#define TYPE_RENDER_WINDOW (render_window_get_type ())
#define RENDER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER_WINDOW, RenderWindow))
#define RENDER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER_WINDOW, RenderWindowClass))
#define IS_RENDER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER_WINDOW))
#define IS_RENDER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER_WINDOW))
#define RENDER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER_WINDOW, RenderWindowClass))

typedef struct _RenderWindow RenderWindow;
typedef struct _RenderWindowClass RenderWindowClass;

#define TYPE_MAIN_MENU (main_menu_get_type ())
#define MAIN_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_MENU, MainMenu))
#define MAIN_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_MENU, MainMenuClass))
#define IS_MAIN_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_MENU))
#define IS_MAIN_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_MENU))
#define MAIN_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_MENU, MainMenuClass))

typedef struct _MainMenu MainMenu;
typedef struct _MainMenuClass MainMenuClass;
typedef struct _MainMenuPrivate MainMenuPrivate;

#define TYPE_MAIN_MENU_BACKGROUND (main_menu_background_get_type ())
#define MAIN_MENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackground))
#define MAIN_MENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackgroundClass))
#define IS_MAIN_MENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_MENU_BACKGROUND))
#define IS_MAIN_MENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_MENU_BACKGROUND))
#define MAIN_MENU_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackgroundClass))

typedef struct _MainMenuBackground MainMenuBackground;
typedef struct _MainMenuBackgroundClass MainMenuBackgroundClass;

#define TYPE_BUTTON (button_get_type ())
#define BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BUTTON, Button))
#define BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BUTTON, ButtonClass))
#define IS_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BUTTON))
#define IS_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BUTTON))
#define BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BUTTON, ButtonClass))

typedef struct _Button Button;
typedef struct _ButtonClass ButtonClass;

#define MAIN_MENU_TYPE_MENU_ACTION (main_menu_menu_action_get_type ())
#define _view_unref0(var) ((var == NULL) ? NULL : (var = (view_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _button_unref0(var) ((var == NULL) ? NULL : (var = (button_unref (var), NULL)))

struct _IResourceStoreIface {
	GTypeInterface parent_iface;
	Render3DObject* (*load_3D_object) (IResourceStore* self, const gchar* name);
};

struct _View {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ViewPrivate * priv;
	RenderWindow* parent_window;
};

struct _ViewClass {
	GTypeClass parent_class;
	void (*finalize) (View *self);
	void (*do_load_resources) (View* self, IResourceStore* store);
	void (*do_render) (View* self, RenderState* state, IResourceStore* store);
	void (*do_process) (View* self, gdouble dt);
	void (*do_mouse_move) (View* self, gint x, gint y);
	void (*do_key_press) (View* self, gchar key);
};

struct _MainMenu {
	View parent_instance;
	MainMenuPrivate * priv;
};

struct _MainMenuClass {
	ViewClass parent_class;
};

typedef enum  {
	MAIN_MENU_MENU_ACTION_ACTIVE,
	MAIN_MENU_MENU_ACTION_SINGLE_PLAYER,
	MAIN_MENU_MENU_ACTION_HOST_MULTI_PLAYER,
	MAIN_MENU_MENU_ACTION_JOIN_MULTI_PLAYER,
	MAIN_MENU_MENU_ACTION_OPTIONS,
	MAIN_MENU_MENU_ACTION_EXIT
} MainMenuMenuAction;

struct _MainMenuPrivate {
	MainMenuBackground* background;
	GeeArrayList* buttons;
	Button* ai_button;
	Button* host_button;
	Button* join_button;
	Button* exit_button;
	MainMenuMenuAction _action;
};


static gpointer main_menu_parent_class = NULL;

gpointer view_ref (gpointer instance);
void view_unref (gpointer instance);
GParamSpec* param_spec_view (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_view (GValue* value, gpointer v_object);
void value_take_view (GValue* value, gpointer v_object);
gpointer value_get_view (const GValue* value);
GType view_get_type (void) G_GNUC_CONST;
gpointer render3_dobject_ref (gpointer instance);
void render3_dobject_unref (gpointer instance);
GParamSpec* param_spec_render3_dobject (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_render3_dobject (GValue* value, gpointer v_object);
void value_take_render3_dobject (GValue* value, gpointer v_object);
gpointer value_get_render3_dobject (const GValue* value);
GType render3_dobject_get_type (void) G_GNUC_CONST;
GType iresource_store_get_type (void) G_GNUC_CONST;
gpointer render_state_ref (gpointer instance);
void render_state_unref (gpointer instance);
GParamSpec* param_spec_render_state (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_render_state (GValue* value, gpointer v_object);
void value_take_render_state (GValue* value, gpointer v_object);
gpointer value_get_render_state (const GValue* value);
GType render_state_get_type (void) G_GNUC_CONST;
gpointer render_window_ref (gpointer instance);
void render_window_unref (gpointer instance);
GParamSpec* param_spec_render_window (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_render_window (GValue* value, gpointer v_object);
void value_take_render_window (GValue* value, gpointer v_object);
gpointer value_get_render_window (const GValue* value);
GType render_window_get_type (void) G_GNUC_CONST;
GType main_menu_get_type (void) G_GNUC_CONST;
GType main_menu_background_get_type (void) G_GNUC_CONST;
gpointer button_ref (gpointer instance);
void button_unref (gpointer instance);
GParamSpec* param_spec_button (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_button (GValue* value, gpointer v_object);
void value_take_button (GValue* value, gpointer v_object);
gpointer value_get_button (const GValue* value);
GType button_get_type (void) G_GNUC_CONST;
GType main_menu_menu_action_get_type (void) G_GNUC_CONST;
#define MAIN_MENU_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_MENU, MainMenuPrivate))
enum  {
	MAIN_MENU_DUMMY_PROPERTY
};
static void main_menu_ai_button_press (MainMenu* self, Button* b);
static void _main_menu_ai_button_press_button_press (Button* _sender, gpointer self);
static void main_menu_host_button_press (MainMenu* self, Button* b);
static void _main_menu_host_button_press_button_press (Button* _sender, gpointer self);
static void main_menu_join_button_press (MainMenu* self, Button* b);
static void _main_menu_join_button_press_button_press (Button* _sender, gpointer self);
static void main_menu_exit_button_press (MainMenu* self, Button* b);
static void _main_menu_exit_button_press_button_press (Button* _sender, gpointer self);
MainMenuBackground* main_menu_background_new (void);
MainMenuBackground* main_menu_background_construct (GType object_type);
MainMenu* main_menu_new (void);
MainMenu* main_menu_construct (GType object_type);
View* view_construct (GType object_type);
void view_add_child (View* self, View* child);
static void main_menu_real_do_mouse_move (View* base, gint x, gint y);
static void main_menu_real_do_key_press (View* base, gchar key);
static void main_menu_real_do_load_resources (View* base, IResourceStore* store);
static void main_menu_real_do_process (View* base, gdouble dt);
static void main_menu_real_do_render (View* base, RenderState* state, IResourceStore* store);
static void main_menu_set_action (MainMenu* self, MainMenuMenuAction value);
MainMenuMenuAction main_menu_get_action (MainMenu* self);
static void main_menu_finalize (View* obj);


static void _main_menu_ai_button_press_button_press (Button* _sender, gpointer self) {
	main_menu_ai_button_press (self, _sender);
}


static void _main_menu_host_button_press_button_press (Button* _sender, gpointer self) {
	main_menu_host_button_press (self, _sender);
}


static void _main_menu_join_button_press_button_press (Button* _sender, gpointer self) {
	main_menu_join_button_press (self, _sender);
}


static void _main_menu_exit_button_press_button_press (Button* _sender, gpointer self) {
	main_menu_exit_button_press (self, _sender);
}


GType main_menu_menu_action_get_type (void) {
	static volatile gsize main_menu_menu_action_type_id__volatile = 0;
	if (g_once_init_enter (&main_menu_menu_action_type_id__volatile)) {
		static const GEnumValue values[] = {{MAIN_MENU_MENU_ACTION_ACTIVE, "MAIN_MENU_MENU_ACTION_ACTIVE", "active"}, {MAIN_MENU_MENU_ACTION_SINGLE_PLAYER, "MAIN_MENU_MENU_ACTION_SINGLE_PLAYER", "single-player"}, {MAIN_MENU_MENU_ACTION_HOST_MULTI_PLAYER, "MAIN_MENU_MENU_ACTION_HOST_MULTI_PLAYER", "host-multi-player"}, {MAIN_MENU_MENU_ACTION_JOIN_MULTI_PLAYER, "MAIN_MENU_MENU_ACTION_JOIN_MULTI_PLAYER", "join-multi-player"}, {MAIN_MENU_MENU_ACTION_OPTIONS, "MAIN_MENU_MENU_ACTION_OPTIONS", "options"}, {MAIN_MENU_MENU_ACTION_EXIT, "MAIN_MENU_MENU_ACTION_EXIT", "exit"}, {0, NULL, NULL}};
		GType main_menu_menu_action_type_id;
		main_menu_menu_action_type_id = g_enum_register_static ("MainMenuMenuAction", values);
		g_once_init_leave (&main_menu_menu_action_type_id__volatile, main_menu_menu_action_type_id);
	}
	return main_menu_menu_action_type_id__volatile;
}


MainMenu* main_menu_construct (GType object_type) {
	MainMenu* self = NULL;
	self = (MainMenu*) view_construct (object_type);
	view_add_child ((View*) self, (View*) self->priv->background);
	return self;
}


MainMenu* main_menu_new (void) {
	return main_menu_construct (TYPE_MAIN_MENU);
}


static void main_menu_real_do_mouse_move (View* base, gint x, gint y) {
	MainMenu * self;
	self = (MainMenu*) base;
}


static void main_menu_real_do_key_press (View* base, gchar key) {
	MainMenu * self;
	self = (MainMenu*) base;
}


static void main_menu_real_do_load_resources (View* base, IResourceStore* store) {
	MainMenu * self;
	self = (MainMenu*) base;
	g_return_if_fail (store != NULL);
}


static void main_menu_real_do_process (View* base, gdouble dt) {
	MainMenu * self;
	self = (MainMenu*) base;
}


static void main_menu_real_do_render (View* base, RenderState* state, IResourceStore* store) {
	MainMenu * self;
	self = (MainMenu*) base;
	g_return_if_fail (state != NULL);
	g_return_if_fail (store != NULL);
}


static void main_menu_ai_button_press (MainMenu* self, Button* b) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (b != NULL);
	main_menu_set_action (self, MAIN_MENU_MENU_ACTION_SINGLE_PLAYER);
	g_signal_emit_by_name (self, "menu-action");
}


static void main_menu_host_button_press (MainMenu* self, Button* b) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (b != NULL);
	main_menu_set_action (self, MAIN_MENU_MENU_ACTION_HOST_MULTI_PLAYER);
	g_signal_emit_by_name (self, "menu-action");
}


static void main_menu_join_button_press (MainMenu* self, Button* b) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (b != NULL);
	main_menu_set_action (self, MAIN_MENU_MENU_ACTION_JOIN_MULTI_PLAYER);
	g_signal_emit_by_name (self, "menu-action");
}


static void main_menu_exit_button_press (MainMenu* self, Button* b) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (b != NULL);
	main_menu_set_action (self, MAIN_MENU_MENU_ACTION_EXIT);
	g_signal_emit_by_name (self, "menu-action");
}


MainMenuMenuAction main_menu_get_action (MainMenu* self) {
	MainMenuMenuAction result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_action;
	return result;
}


static void main_menu_set_action (MainMenu* self, MainMenuMenuAction value) {
	g_return_if_fail (self != NULL);
	self->priv->_action = value;
}


static void main_menu_class_init (MainMenuClass * klass) {
	main_menu_parent_class = g_type_class_peek_parent (klass);
	VIEW_CLASS (klass)->finalize = main_menu_finalize;
	g_type_class_add_private (klass, sizeof (MainMenuPrivate));
	VIEW_CLASS (klass)->do_mouse_move = main_menu_real_do_mouse_move;
	VIEW_CLASS (klass)->do_key_press = main_menu_real_do_key_press;
	VIEW_CLASS (klass)->do_load_resources = main_menu_real_do_load_resources;
	VIEW_CLASS (klass)->do_process = main_menu_real_do_process;
	VIEW_CLASS (klass)->do_render = main_menu_real_do_render;
	g_signal_new ("menu_action", TYPE_MAIN_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void main_menu_instance_init (MainMenu * self) {
	MainMenuBackground* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self->priv = MAIN_MENU_GET_PRIVATE (self);
	_tmp0_ = main_menu_background_new ();
	self->priv->background = _tmp0_;
	_tmp1_ = gee_array_list_new (TYPE_BUTTON, (GBoxedCopyFunc) button_ref, button_unref, NULL);
	self->priv->buttons = _tmp1_;
}


static void main_menu_finalize (View* obj) {
	MainMenu * self;
	guint _tmp0_;
	guint _tmp1_;
	guint _tmp2_;
	guint _tmp3_;
	self = MAIN_MENU (obj);
	g_signal_parse_name ("press", TYPE_BUTTON, &_tmp0_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->ai_button, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _main_menu_ai_button_press_button_press, self);
	g_signal_parse_name ("press", TYPE_BUTTON, &_tmp1_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->host_button, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _main_menu_host_button_press_button_press, self);
	g_signal_parse_name ("press", TYPE_BUTTON, &_tmp2_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->join_button, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _main_menu_join_button_press_button_press, self);
	g_signal_parse_name ("press", TYPE_BUTTON, &_tmp3_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->exit_button, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp3_, 0, NULL, (GCallback) _main_menu_exit_button_press_button_press, self);
	_view_unref0 (self->priv->background);
	_g_object_unref0 (self->priv->buttons);
	_button_unref0 (self->priv->ai_button);
	_button_unref0 (self->priv->host_button);
	_button_unref0 (self->priv->join_button);
	_button_unref0 (self->priv->exit_button);
	VIEW_CLASS (main_menu_parent_class)->finalize (obj);
}


GType main_menu_get_type (void) {
	static volatile gsize main_menu_type_id__volatile = 0;
	if (g_once_init_enter (&main_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainMenu), 0, (GInstanceInitFunc) main_menu_instance_init, NULL };
		GType main_menu_type_id;
		main_menu_type_id = g_type_register_static (TYPE_VIEW, "MainMenu", &g_define_type_info, 0);
		g_once_init_leave (&main_menu_type_id__volatile, main_menu_type_id);
	}
	return main_menu_type_id__volatile;
}



