/* MainMenuBackground.c generated by valac 0.16.1, the Vala compiler
 * generated from MainMenuBackground.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <GL/glew.h>
#include <gobject/gvaluecollector.h>


#define TYPE_MAIN_MENU_BACKGROUND (main_menu_background_get_type ())
#define MAIN_MENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackground))
#define MAIN_MENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackgroundClass))
#define IS_MAIN_MENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_MENU_BACKGROUND))
#define IS_MAIN_MENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_MENU_BACKGROUND))
#define MAIN_MENU_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackgroundClass))

typedef struct _MainMenuBackground MainMenuBackground;
typedef struct _MainMenuBackgroundClass MainMenuBackgroundClass;
typedef struct _MainMenuBackgroundPrivate MainMenuBackgroundPrivate;

#define TYPE_TEXTURE (texture_get_type ())
#define TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE, Texture))
#define TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE, TextureClass))
#define IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE))
#define IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE))
#define TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE, TextureClass))

typedef struct _Texture Texture;
typedef struct _TextureClass TextureClass;

#define TYPE_TILE (tile_get_type ())
#define TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILE, Tile))
#define TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILE, TileClass))
#define IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILE))
#define IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILE))
#define TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILE, TileClass))

typedef struct _Tile Tile;
typedef struct _TileClass TileClass;
#define _texture_unref0(var) ((var == NULL) ? NULL : (var = (texture_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_TILE_TYPE (tile_type_get_type ())

#define TYPE_VECTOR (vector_get_type ())
#define VECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VECTOR, Vector))
#define VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VECTOR, VectorClass))
#define IS_VECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VECTOR))
#define IS_VECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VECTOR))
#define VECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VECTOR, VectorClass))

typedef struct _Vector Vector;
typedef struct _VectorClass VectorClass;
#define _vector_unref0(var) ((var == NULL) ? NULL : (var = (vector_unref (var), NULL)))
typedef struct _ParamSpecMainMenuBackground ParamSpecMainMenuBackground;

struct _MainMenuBackground {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MainMenuBackgroundPrivate * priv;
};

struct _MainMenuBackgroundClass {
	GTypeClass parent_class;
	void (*finalize) (MainMenuBackground *self);
};

struct _MainMenuBackgroundPrivate {
	Texture* table_texture;
	Tile* tile;
	gdouble rotation;
};

typedef enum  {
	TILE_TYPE_MAN1 = 0,
	TILE_TYPE_MAN2,
	TILE_TYPE_MAN3,
	TILE_TYPE_MAN4,
	TILE_TYPE_MAN5,
	TILE_TYPE_MAN6,
	TILE_TYPE_MAN7,
	TILE_TYPE_MAN8,
	TILE_TYPE_MAN9,
	TILE_TYPE_PIN1,
	TILE_TYPE_PIN2,
	TILE_TYPE_PIN3,
	TILE_TYPE_PIN4,
	TILE_TYPE_PIN5,
	TILE_TYPE_PIN6,
	TILE_TYPE_PIN7,
	TILE_TYPE_PIN8,
	TILE_TYPE_PIN9,
	TILE_TYPE_SOU1,
	TILE_TYPE_SOU2,
	TILE_TYPE_SOU3,
	TILE_TYPE_SOU4,
	TILE_TYPE_SOU5,
	TILE_TYPE_SOU6,
	TILE_TYPE_SOU7,
	TILE_TYPE_SOU8,
	TILE_TYPE_SOU9,
	TILE_TYPE_HIGASHI,
	TILE_TYPE_MINAMI,
	TILE_TYPE_NISHI,
	TILE_TYPE_KITA,
	TILE_TYPE_HATSU,
	TILE_TYPE_HAKU,
	TILE_TYPE_CHUN
} TILE_TYPE;

struct _ParamSpecMainMenuBackground {
	GParamSpec parent_instance;
};


static gpointer main_menu_background_parent_class = NULL;

gpointer main_menu_background_ref (gpointer instance);
void main_menu_background_unref (gpointer instance);
GParamSpec* param_spec_main_menu_background (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_main_menu_background (GValue* value, gpointer v_object);
void value_take_main_menu_background (GValue* value, gpointer v_object);
gpointer value_get_main_menu_background (const GValue* value);
GType main_menu_background_get_type (void) G_GNUC_CONST;
gpointer texture_ref (gpointer instance);
void texture_unref (gpointer instance);
GParamSpec* param_spec_texture (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_texture (GValue* value, gpointer v_object);
void value_take_texture (GValue* value, gpointer v_object);
gpointer value_get_texture (const GValue* value);
GType texture_get_type (void) G_GNUC_CONST;
GType tile_get_type (void) G_GNUC_CONST;
#define MAIN_MENU_BACKGROUND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_MENU_BACKGROUND, MainMenuBackgroundPrivate))
enum  {
	MAIN_MENU_BACKGROUND_DUMMY_PROPERTY
};
MainMenuBackground* main_menu_background_new (void);
MainMenuBackground* main_menu_background_construct (GType object_type);
Texture* texture_load_texture (const gchar* name);
GType tile_type_get_type (void) G_GNUC_CONST;
Tile* tile_new (gfloat size, gint id, gint type);
Tile* tile_construct (GType object_type, gfloat size, gint id, gint type);
#define TILE_tile_size 0.1f
#define TILE_TILE_HEIGHT (2.6f * TILE_tile_size)
Vector* vector_new (gfloat x, gfloat y, gfloat z);
Vector* vector_construct (GType object_type, gfloat x, gfloat y, gfloat z);
gpointer vector_ref (gpointer instance);
void vector_unref (gpointer instance);
GParamSpec* param_spec_vector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_vector (GValue* value, gpointer v_object);
void value_take_vector (GValue* value, gpointer v_object);
gpointer value_get_vector (const GValue* value);
GType vector_get_type (void) G_GNUC_CONST;
void tile_set_position (Tile* self, Vector* value);
void main_menu_background_process (MainMenuBackground* self, gdouble dt);
void main_menu_background_render (MainMenuBackground* self);
GLuint texture_get_texture (Texture* self);
void tile_render (Tile* self);
static void main_menu_background_finalize (MainMenuBackground* obj);


MainMenuBackground* main_menu_background_construct (GType object_type) {
	MainMenuBackground* self = NULL;
	Texture* _tmp0_ = NULL;
	Tile* _tmp1_;
	Tile* _tmp2_;
	Vector* _tmp3_;
	Vector* _tmp4_;
#line 10 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self = (MainMenuBackground*) g_type_create_instance (object_type);
#line 12 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp0_ = texture_load_texture ("table");
#line 12 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_texture_unref0 (self->priv->table_texture);
#line 12 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->priv->table_texture = _tmp0_;
#line 13 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp1_ = tile_new ((gfloat) 1, -1, (gint) TILE_TYPE_PIN1);
#line 13 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_g_object_unref0 (self->priv->tile);
#line 13 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->priv->tile = _tmp1_;
#line 14 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp2_ = self->priv->tile;
#line 14 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp3_ = vector_new ((gfloat) 0, (-TILE_TILE_HEIGHT) / 2, (gfloat) 0);
#line 14 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp4_ = _tmp3_;
#line 14 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	tile_set_position (_tmp2_, _tmp4_);
#line 14 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_vector_unref0 (_tmp4_);
#line 10 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return self;
#line 201 "MainMenuBackground.c"
}


MainMenuBackground* main_menu_background_new (void) {
#line 10 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return main_menu_background_construct (TYPE_MAIN_MENU_BACKGROUND);
#line 208 "MainMenuBackground.c"
}


void main_menu_background_process (MainMenuBackground* self, gdouble dt) {
	gdouble _tmp0_;
	gdouble _tmp1_;
#line 17 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_if_fail (self != NULL);
#line 19 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp0_ = self->priv->rotation;
#line 19 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp1_ = dt;
#line 19 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->priv->rotation = _tmp0_ + (_tmp1_ * 1);
#line 223 "MainMenuBackground.c"
}


void main_menu_background_render (MainMenuBackground* self) {
	gfloat tex_u_max;
	gfloat tex_v_max;
	gfloat size;
	gdouble _tmp0_;
	Texture* _tmp1_;
	GLuint _tmp2_;
	GLuint _tmp3_;
	Tile* _tmp4_;
#line 22 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	tex_u_max = 10.0f;
#line 25 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	tex_v_max = 10.0f;
#line 26 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	size = (gfloat) 1;
#line 28 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp0_ = self->priv->rotation;
#line 28 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glRotatef (-((GLfloat) _tmp0_), (GLfloat) 0, (GLfloat) 0, (GLfloat) 1);
#line 30 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glEnable ((GLenum) GL_TEXTURE_2D);
#line 31 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp1_ = self->priv->table_texture;
#line 31 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp2_ = texture_get_texture (_tmp1_);
#line 31 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp3_ = _tmp2_;
#line 31 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glBindTexture ((GLenum) GL_TEXTURE_2D, _tmp3_);
#line 32 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_S, GL_MIRRORED_REPEAT);
#line 33 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexParameteri ((GLenum) GL_TEXTURE_2D, (GLenum) GL_TEXTURE_WRAP_T, GL_MIRRORED_REPEAT);
#line 35 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glBegin ((GLenum) GL_QUADS);
#line 37 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexCoord2f ((GLfloat) 0.0f, (GLfloat) tex_v_max);
#line 38 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glVertex3f (-((GLfloat) size), -((GLfloat) size), (GLfloat) 0);
#line 39 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexCoord2f ((GLfloat) tex_u_max, (GLfloat) tex_v_max);
#line 40 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glVertex3f ((GLfloat) size, -((GLfloat) size), (GLfloat) 0);
#line 41 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexCoord2f ((GLfloat) tex_u_max, (GLfloat) 0.0f);
#line 42 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glVertex3f ((GLfloat) size, (GLfloat) size, (GLfloat) 0);
#line 43 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glTexCoord2f ((GLfloat) 0.0f, (GLfloat) 0.0f);
#line 44 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glVertex3f (-((GLfloat) size), (GLfloat) size, (GLfloat) 0);
#line 46 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	glEnd ();
#line 48 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_tmp4_ = self->priv->tile;
#line 48 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	tile_render (_tmp4_);
#line 286 "MainMenuBackground.c"
}


static void value_main_menu_background_init (GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	value->data[0].v_pointer = NULL;
#line 293 "MainMenuBackground.c"
}


static void value_main_menu_background_free_value (GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		main_menu_background_unref (value->data[0].v_pointer);
#line 302 "MainMenuBackground.c"
	}
}


static void value_main_menu_background_copy_value (const GValue* src_value, GValue* dest_value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (src_value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		dest_value->data[0].v_pointer = main_menu_background_ref (src_value->data[0].v_pointer);
#line 312 "MainMenuBackground.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		dest_value->data[0].v_pointer = NULL;
#line 316 "MainMenuBackground.c"
	}
}


static gpointer value_main_menu_background_peek_pointer (const GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return value->data[0].v_pointer;
#line 324 "MainMenuBackground.c"
}


static gchar* value_main_menu_background_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (collect_values[0].v_pointer) {
#line 331 "MainMenuBackground.c"
		MainMenuBackground* object;
		object = collect_values[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		if (object->parent_instance.g_class == NULL) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 338 "MainMenuBackground.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 342 "MainMenuBackground.c"
		}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = main_menu_background_ref (object);
#line 346 "MainMenuBackground.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = NULL;
#line 350 "MainMenuBackground.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return NULL;
#line 354 "MainMenuBackground.c"
}


static gchar* value_main_menu_background_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	MainMenuBackground** object_p;
	object_p = collect_values[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (!object_p) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 365 "MainMenuBackground.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (!value->data[0].v_pointer) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		*object_p = NULL;
#line 371 "MainMenuBackground.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		*object_p = value->data[0].v_pointer;
#line 375 "MainMenuBackground.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		*object_p = main_menu_background_ref (value->data[0].v_pointer);
#line 379 "MainMenuBackground.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return NULL;
#line 383 "MainMenuBackground.c"
}


GParamSpec* param_spec_main_menu_background (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecMainMenuBackground* spec;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_MAIN_MENU_BACKGROUND), NULL);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return G_PARAM_SPEC (spec);
#line 397 "MainMenuBackground.c"
}


gpointer value_get_main_menu_background (const GValue* value) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN_MENU_BACKGROUND), NULL);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return value->data[0].v_pointer;
#line 406 "MainMenuBackground.c"
}


void value_set_main_menu_background (GValue* value, gpointer v_object) {
	MainMenuBackground* old;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN_MENU_BACKGROUND));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (v_object) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN_MENU_BACKGROUND));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = v_object;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		main_menu_background_ref (value->data[0].v_pointer);
#line 426 "MainMenuBackground.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = NULL;
#line 430 "MainMenuBackground.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (old) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		main_menu_background_unref (old);
#line 436 "MainMenuBackground.c"
	}
}


void value_take_main_menu_background (GValue* value, gpointer v_object) {
	MainMenuBackground* old;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN_MENU_BACKGROUND));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (v_object) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN_MENU_BACKGROUND));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = v_object;
#line 455 "MainMenuBackground.c"
	} else {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		value->data[0].v_pointer = NULL;
#line 459 "MainMenuBackground.c"
	}
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (old) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		main_menu_background_unref (old);
#line 465 "MainMenuBackground.c"
	}
}


static void main_menu_background_class_init (MainMenuBackgroundClass * klass) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	main_menu_background_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	MAIN_MENU_BACKGROUND_CLASS (klass)->finalize = main_menu_background_finalize;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_type_class_add_private (klass, sizeof (MainMenuBackgroundPrivate));
#line 477 "MainMenuBackground.c"
}


static void main_menu_background_instance_init (MainMenuBackground * self) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->priv = MAIN_MENU_BACKGROUND_GET_PRIVATE (self);
#line 8 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->priv->rotation = (gdouble) 0;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self->ref_count = 1;
#line 488 "MainMenuBackground.c"
}


static void main_menu_background_finalize (MainMenuBackground* obj) {
	MainMenuBackground * self;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	self = MAIN_MENU_BACKGROUND (obj);
#line 5 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_texture_unref0 (self->priv->table_texture);
#line 6 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	_g_object_unref0 (self->priv->tile);
#line 500 "MainMenuBackground.c"
}


GType main_menu_background_get_type (void) {
	static volatile gsize main_menu_background_type_id__volatile = 0;
	if (g_once_init_enter (&main_menu_background_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_main_menu_background_init, value_main_menu_background_free_value, value_main_menu_background_copy_value, value_main_menu_background_peek_pointer, "p", value_main_menu_background_collect_value, "p", value_main_menu_background_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (MainMenuBackgroundClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_menu_background_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainMenuBackground), 0, (GInstanceInitFunc) main_menu_background_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType main_menu_background_type_id;
		main_menu_background_type_id = g_type_register_fundamental (g_type_fundamental_next (), "MainMenuBackground", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&main_menu_background_type_id__volatile, main_menu_background_type_id);
	}
	return main_menu_background_type_id__volatile;
}


gpointer main_menu_background_ref (gpointer instance) {
	MainMenuBackground* self;
	self = instance;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	g_atomic_int_inc (&self->ref_count);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	return instance;
#line 525 "MainMenuBackground.c"
}


void main_menu_background_unref (gpointer instance) {
	MainMenuBackground* self;
	self = instance;
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		MAIN_MENU_BACKGROUND_GET_CLASS (self)->finalize (self);
#line 3 "/home/fluffy/RiichiMahjong/source/Menu/MainMenuBackground.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 538 "MainMenuBackground.c"
	}
}



