/* Bot.c generated by valac 0.12.0, the Vala compiler
 * generated from Bot.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define TYPE_BOT (bot_get_type ())
#define BOT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOT, Bot))
#define BOT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BOT, BotClass))
#define IS_BOT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOT))
#define IS_BOT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BOT))
#define BOT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOT, BotClass))

typedef struct _Bot Bot;
typedef struct _BotClass BotClass;
typedef struct _BotPrivate BotPrivate;

#define TYPE_PLAYER (player_get_type ())
#define PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PLAYER, Player))
#define PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PLAYER, PlayerClass))
#define IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PLAYER))
#define IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PLAYER))
#define PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PLAYER, PlayerClass))

typedef struct _Player Player;
typedef struct _PlayerClass PlayerClass;

#define TYPE_COMPUTER_PLAYER (computer_player_get_type ())
#define COMPUTER_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPUTER_PLAYER, ComputerPlayer))
#define COMPUTER_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPUTER_PLAYER, ComputerPlayerClass))
#define IS_COMPUTER_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPUTER_PLAYER))
#define IS_COMPUTER_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPUTER_PLAYER))
#define COMPUTER_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPUTER_PLAYER, ComputerPlayerClass))

typedef struct _ComputerPlayer ComputerPlayer;
typedef struct _ComputerPlayerClass ComputerPlayerClass;

#define TYPE_TILE (tile_get_type ())
#define TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILE, Tile))
#define TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILE, TileClass))
#define IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILE))
#define IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILE))
#define TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILE, TileClass))

typedef struct _Tile Tile;
typedef struct _TileClass TileClass;

#define TYPE_CALL_ACTION (call_action_get_type ())
#define CALL_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CALL_ACTION, CallAction))
#define CALL_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CALL_ACTION, CallActionClass))
#define IS_CALL_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CALL_ACTION))
#define IS_CALL_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CALL_ACTION))
#define CALL_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CALL_ACTION, CallActionClass))

typedef struct _CallAction CallAction;
typedef struct _CallActionClass CallActionClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CALL_ACTION_TYPE_CALL_ACTION_ENUM (call_action_call_action_enum_get_type ())

#define TYPE_TURN_ACTION (turn_action_get_type ())
#define TURN_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TURN_ACTION, TurnAction))
#define TURN_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TURN_ACTION, TurnActionClass))
#define IS_TURN_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TURN_ACTION))
#define IS_TURN_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TURN_ACTION))
#define TURN_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TURN_ACTION, TurnActionClass))

typedef struct _TurnAction TurnAction;
typedef struct _TurnActionClass TurnActionClass;

#define TYPE_CALL (call_get_type ())
#define CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CALL, Call))
#define CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CALL, CallClass))
#define IS_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CALL))
#define IS_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CALL))
#define CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CALL, CallClass))

typedef struct _Call Call;
typedef struct _CallClass CallClass;

#define TYPE_PON (pon_get_type ())
#define PON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PON, Pon))
#define PON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PON, PonClass))
#define IS_PON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PON))
#define IS_PON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PON))
#define PON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PON, PonClass))

typedef struct _Pon Pon;
typedef struct _PonClass PonClass;
#define _call_unref0(var) ((var == NULL) ? NULL : (var = (call_unref (var), NULL)))
typedef struct _ParamSpecBot ParamSpecBot;

struct _Bot {
	GTypeInstance parent_instance;
	volatile int ref_count;
	BotPrivate * priv;
};

struct _BotClass {
	GTypeClass parent_class;
	void (*finalize) (Bot *self);
};

typedef enum  {
	CALL_ACTION_CALL_ACTION_ENUM_NONE,
	CALL_ACTION_CALL_ACTION_ENUM_OPEN_KAN,
	CALL_ACTION_CALL_ACTION_ENUM_PON,
	CALL_ACTION_CALL_ACTION_ENUM_CHI,
	CALL_ACTION_CALL_ACTION_ENUM_RON
} CallActionCallActionEnum;

struct _ParamSpecBot {
	GParamSpec parent_instance;
};


static gpointer bot_parent_class = NULL;
static gulong bot_decision_delay;
static gulong bot_decision_delay = (gulong) 700000;

gpointer bot_ref (gpointer instance);
void bot_unref (gpointer instance);
GParamSpec* param_spec_bot (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_bot (GValue* value, gpointer v_object);
void value_take_bot (GValue* value, gpointer v_object);
gpointer value_get_bot (const GValue* value);
GType bot_get_type (void) G_GNUC_CONST;
enum  {
	BOT_DUMMY_PROPERTY
};
GType player_get_type (void) G_GNUC_CONST;
GType computer_player_get_type (void) G_GNUC_CONST;
GType tile_get_type (void) G_GNUC_CONST;
gpointer call_action_ref (gpointer instance);
void call_action_unref (gpointer instance);
GParamSpec* param_spec_call_action (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_call_action (GValue* value, gpointer v_object);
void value_take_call_action (GValue* value, gpointer v_object);
gpointer value_get_call_action (const GValue* value);
GType call_action_get_type (void) G_GNUC_CONST;
CallAction* bot_make_call (gint bot_level, ComputerPlayer* player, Tile* discard_tile, gboolean can_chi);
CallAction* call_action_new_none (void);
CallAction* call_action_construct_none (GType object_type);
static void bot_delay (void);
gboolean logic_can_win_with (GeeArrayList* hand, Tile* tile);
GeeArrayList* player_get_hand (Player* self);
gboolean logic_has_yaku (Player* player, Tile* ron_tile, gboolean last_piece, gboolean kan_piece);
guint8 tile_get_id (Tile* self);
CallAction* call_action_new_ron (guint8 tile);
CallAction* call_action_construct_ron (GType object_type, guint8 tile);
gboolean logic_can_open_kan (Tile* played_tile, GeeArrayList* hand);
gint tile_get_tile_type (Tile* self);
GType call_action_call_action_enum_get_type (void) G_GNUC_CONST;
guint8* tile_tiles_to_ints (Tile** tiles, int tiles_length1, int* result_length1);
CallAction* call_action_new (CallActionCallActionEnum action, guint8* tiles, int tiles_length1);
CallAction* call_action_construct (GType object_type, CallActionCallActionEnum action, guint8* tiles, int tiles_length1);
gboolean logic_can_pon (Tile* played_tile, GeeArrayList* hand);
gboolean logic_can_chi (Tile* played_tile, GeeArrayList* hand);
gpointer turn_action_ref (gpointer instance);
void turn_action_unref (gpointer instance);
GParamSpec* param_spec_turn_action (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_turn_action (GValue* value, gpointer v_object);
void value_take_turn_action (GValue* value, gpointer v_object);
gpointer value_get_turn_action (const GValue* value);
GType turn_action_get_type (void) G_GNUC_CONST;
TurnAction* bot_make_move (gint bot_level, ComputerPlayer* player);
GRand* environment_get_random (void);
TurnAction* turn_action_new_discard (guint8 discard_tile);
TurnAction* turn_action_construct_discard (GType object_type, guint8 discard_tile);
gboolean logic_winning_hand (GeeArrayList* hand);
TurnAction* turn_action_new_tsumo (void);
TurnAction* turn_action_construct_tsumo (GType object_type);
gboolean player_get_in_riichi (Player* self);
GeeArrayList* logic_can_tenpai (GeeArrayList* hand);
gboolean player_get_open_hand (Player* self);
TurnAction* turn_action_new_riichi (guint8 discard_tile);
TurnAction* turn_action_construct_riichi (GType object_type, guint8 discard_tile);
gboolean logic_can_closed_kan (GeeArrayList* hand);
TurnAction* turn_action_new_closed_kan (guint8* kan, int kan_length1);
TurnAction* turn_action_construct_closed_kan (GType object_type, guint8* kan, int kan_length1);
gpointer call_ref (gpointer instance);
void call_unref (gpointer instance);
GParamSpec* param_spec_call (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_call (GValue* value, gpointer v_object);
void value_take_call (GValue* value, gpointer v_object);
gpointer value_get_call (const GValue* value);
GType call_get_type (void) G_GNUC_CONST;
GType pon_get_type (void) G_GNUC_CONST;
gboolean logic_can_late_kan (GeeArrayList* hand, GeeArrayList* pons);
GeeArrayList* player_get_pons (Player* self);
Tile** call_get_tiles (Call* self, int* result_length1);
TurnAction* turn_action_new_late_kan (guint8 kan_tile, guint8 pon);
TurnAction* turn_action_construct_late_kan (GType object_type, guint8 kan_tile, guint8 pon);
Bot* bot_new (void);
Bot* bot_construct (GType object_type);
static void bot_finalize (Bot* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


CallAction* bot_make_call (gint bot_level, ComputerPlayer* player, Tile* discard_tile, gboolean can_chi) {
	CallAction* result = NULL;
	CallAction* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	GeeArrayList* _tmp2_ = NULL;
	gboolean _tmp3_;
	CallAction* _tmp81_ = NULL;
	g_return_val_if_fail (player != NULL, NULL);
	g_return_val_if_fail (discard_tile != NULL, NULL);
	_tmp0_ = call_action_new_none ();
	result = _tmp0_;
	return result;
	bot_delay ();
	_tmp2_ = player_get_hand ((Player*) player);
	_tmp3_ = logic_can_win_with (_tmp2_, discard_tile);
	if (_tmp3_) {
		gboolean _tmp4_;
		_tmp4_ = logic_has_yaku ((Player*) player, discard_tile, FALSE, FALSE);
		_tmp1_ = _tmp4_;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		guint8 _tmp5_;
		CallAction* _tmp6_ = NULL;
		_tmp5_ = tile_get_id (discard_tile);
		_tmp6_ = call_action_new_ron (_tmp5_);
		result = _tmp6_;
		return result;
	} else {
		GeeArrayList* _tmp7_ = NULL;
		gboolean _tmp8_;
		_tmp7_ = player_get_hand ((Player*) player);
		_tmp8_ = logic_can_open_kan (discard_tile, _tmp7_);
		if (_tmp8_) {
			Tile** _tmp9_ = NULL;
			Tile** tiles;
			gint tiles_length1;
			gint _tiles_size_;
			gint a;
			_tmp9_ = g_new0 (Tile*, 3 + 1);
			tiles = _tmp9_;
			tiles_length1 = 3;
			_tiles_size_ = 3;
			a = 0;
			{
				GeeArrayList* _tmp10_ = NULL;
				GeeArrayList* _tmp11_;
				GeeArrayList* _t_list;
				gint _tmp12_;
				gint _t_size;
				gint _t_index;
				_tmp10_ = player_get_hand ((Player*) player);
				_tmp11_ = _g_object_ref0 (_tmp10_);
				_t_list = _tmp11_;
				_tmp12_ = gee_collection_get_size ((GeeCollection*) _t_list);
				_t_size = _tmp12_;
				_t_index = -1;
				while (TRUE) {
					gpointer _tmp13_ = NULL;
					Tile* t;
					gint _tmp14_;
					gint _tmp15_;
					_t_index = _t_index + 1;
					if (!(_t_index < _t_size)) {
						break;
					}
					_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
					t = (Tile*) _tmp13_;
					_tmp14_ = tile_get_tile_type (t);
					_tmp15_ = tile_get_tile_type (discard_tile);
					if (_tmp14_ == _tmp15_) {
						gint _tmp16_;
						Tile* _tmp17_;
						Tile* _tmp18_;
						_tmp16_ = a;
						a = _tmp16_ + 1;
						_tmp17_ = _g_object_ref0 (t);
						_tmp18_ = _tmp17_;
						_g_object_unref0 (tiles[_tmp16_]);
						tiles[_tmp16_] = _tmp18_;
					}
					if (a == 3) {
						gint _tmp19_;
						guint8* _tmp20_ = NULL;
						guint8* _tmp21_;
						gint _tmp21__length1;
						CallAction* _tmp22_ = NULL;
						CallAction* _tmp23_;
						_tmp20_ = tile_tiles_to_ints (tiles, tiles_length1, &_tmp19_);
						_tmp21_ = _tmp20_;
						_tmp21__length1 = _tmp19_;
						_tmp22_ = call_action_new (CALL_ACTION_CALL_ACTION_ENUM_OPEN_KAN, _tmp21_, _tmp19_);
						_tmp23_ = _tmp22_;
						_tmp21_ = (g_free (_tmp21_), NULL);
						result = _tmp23_;
						_g_object_unref0 (t);
						_g_object_unref0 (_t_list);
						tiles = (_vala_array_free (tiles, tiles_length1, (GDestroyNotify) g_object_unref), NULL);
						return result;
					}
					_g_object_unref0 (t);
				}
				_g_object_unref0 (_t_list);
			}
			tiles = (_vala_array_free (tiles, tiles_length1, (GDestroyNotify) g_object_unref), NULL);
		} else {
			GeeArrayList* _tmp24_ = NULL;
			gboolean _tmp25_;
			_tmp24_ = player_get_hand ((Player*) player);
			_tmp25_ = logic_can_pon (discard_tile, _tmp24_);
			if (_tmp25_) {
				Tile** _tmp26_ = NULL;
				Tile** tiles;
				gint tiles_length1;
				gint _tiles_size_;
				gint a;
				_tmp26_ = g_new0 (Tile*, 2 + 1);
				tiles = _tmp26_;
				tiles_length1 = 2;
				_tiles_size_ = 2;
				a = 0;
				{
					GeeArrayList* _tmp27_ = NULL;
					GeeArrayList* _tmp28_;
					GeeArrayList* _t_list;
					gint _tmp29_;
					gint _t_size;
					gint _t_index;
					_tmp27_ = player_get_hand ((Player*) player);
					_tmp28_ = _g_object_ref0 (_tmp27_);
					_t_list = _tmp28_;
					_tmp29_ = gee_collection_get_size ((GeeCollection*) _t_list);
					_t_size = _tmp29_;
					_t_index = -1;
					while (TRUE) {
						gpointer _tmp30_ = NULL;
						Tile* t;
						gint _tmp31_;
						gint _tmp32_;
						_t_index = _t_index + 1;
						if (!(_t_index < _t_size)) {
							break;
						}
						_tmp30_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
						t = (Tile*) _tmp30_;
						_tmp31_ = tile_get_tile_type (t);
						_tmp32_ = tile_get_tile_type (discard_tile);
						if (_tmp31_ == _tmp32_) {
							gint _tmp33_;
							Tile* _tmp34_;
							Tile* _tmp35_;
							_tmp33_ = a;
							a = _tmp33_ + 1;
							_tmp34_ = _g_object_ref0 (t);
							_tmp35_ = _tmp34_;
							_g_object_unref0 (tiles[_tmp33_]);
							tiles[_tmp33_] = _tmp35_;
						}
						if (a == 2) {
							gint _tmp36_;
							guint8* _tmp37_ = NULL;
							guint8* _tmp38_;
							gint _tmp38__length1;
							CallAction* _tmp39_ = NULL;
							CallAction* _tmp40_;
							_tmp37_ = tile_tiles_to_ints (tiles, tiles_length1, &_tmp36_);
							_tmp38_ = _tmp37_;
							_tmp38__length1 = _tmp36_;
							_tmp39_ = call_action_new (CALL_ACTION_CALL_ACTION_ENUM_PON, _tmp38_, _tmp36_);
							_tmp40_ = _tmp39_;
							_tmp38_ = (g_free (_tmp38_), NULL);
							result = _tmp40_;
							_g_object_unref0 (t);
							_g_object_unref0 (_t_list);
							tiles = (_vala_array_free (tiles, tiles_length1, (GDestroyNotify) g_object_unref), NULL);
							return result;
						}
						_g_object_unref0 (t);
					}
					_g_object_unref0 (_t_list);
				}
				tiles = (_vala_array_free (tiles, tiles_length1, (GDestroyNotify) g_object_unref), NULL);
			} else {
				GeeArrayList* _tmp41_ = NULL;
				gboolean _tmp42_;
				_tmp41_ = player_get_hand ((Player*) player);
				_tmp42_ = logic_can_chi (discard_tile, _tmp41_);
				if (_tmp42_) {
					Tile* two_less;
					Tile* one_less;
					Tile* one_more;
					Tile* two_more;
					gint _tmp43_;
					gint _tmp44_;
					gint type;
					Tile** _tmp60_ = NULL;
					Tile** tiles;
					gint tiles_length1;
					gint _tiles_size_;
					gboolean _tmp61_ = FALSE;
					gint _tmp76_;
					guint8* _tmp77_ = NULL;
					guint8* _tmp78_;
					gint _tmp78__length1;
					CallAction* _tmp79_ = NULL;
					CallAction* _tmp80_;
					two_less = NULL;
					one_less = NULL;
					one_more = NULL;
					two_more = NULL;
					_tmp43_ = tile_get_tile_type (discard_tile);
					_tmp44_ = tile_get_tile_type (discard_tile);
					type = _tmp43_ - (_tmp44_ % 9);
					{
						GeeArrayList* _tmp45_ = NULL;
						GeeArrayList* _tmp46_;
						GeeArrayList* _t_list;
						gint _tmp47_;
						gint _t_size;
						gint _t_index;
						_tmp45_ = player_get_hand ((Player*) player);
						_tmp46_ = _g_object_ref0 (_tmp45_);
						_t_list = _tmp46_;
						_tmp47_ = gee_collection_get_size ((GeeCollection*) _t_list);
						_t_size = _tmp47_;
						_t_index = -1;
						while (TRUE) {
							gpointer _tmp48_ = NULL;
							Tile* t;
							gboolean _tmp49_ = FALSE;
							gboolean _tmp50_ = FALSE;
							gint _tmp51_;
							gint _tmp54_;
							gint _tmp55_;
							_t_index = _t_index + 1;
							if (!(_t_index < _t_size)) {
								break;
							}
							_tmp48_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
							t = (Tile*) _tmp48_;
							_tmp51_ = tile_get_tile_type (t);
							if (_tmp51_ < type) {
								_tmp50_ = TRUE;
							} else {
								gint _tmp52_;
								_tmp52_ = tile_get_tile_type (t);
								_tmp50_ = _tmp52_ >= (type + 9);
							}
							if (_tmp50_) {
								_tmp49_ = TRUE;
							} else {
								gint _tmp53_;
								_tmp53_ = tile_get_tile_type (t);
								_tmp49_ = _tmp53_ > 26;
							}
							if (_tmp49_) {
								_g_object_unref0 (t);
								continue;
							}
							_tmp54_ = tile_get_tile_type (discard_tile);
							_tmp55_ = tile_get_tile_type (t);
							switch (_tmp54_ - _tmp55_) {
								case -2:
								{
									Tile* _tmp56_;
									_tmp56_ = _g_object_ref0 (t);
									_g_object_unref0 (two_less);
									two_less = _tmp56_;
									break;
								}
								case -1:
								{
									Tile* _tmp57_;
									_tmp57_ = _g_object_ref0 (t);
									_g_object_unref0 (one_less);
									one_less = _tmp57_;
									break;
								}
								case 1:
								{
									Tile* _tmp58_;
									_tmp58_ = _g_object_ref0 (t);
									_g_object_unref0 (one_more);
									one_more = _tmp58_;
									break;
								}
								case 2:
								{
									Tile* _tmp59_;
									_tmp59_ = _g_object_ref0 (t);
									_g_object_unref0 (two_more);
									two_more = _tmp59_;
									break;
								}
								default:
								break;
							}
							_g_object_unref0 (t);
						}
						_g_object_unref0 (_t_list);
					}
					_tmp60_ = g_new0 (Tile*, 2 + 1);
					tiles = _tmp60_;
					tiles_length1 = 2;
					_tiles_size_ = 2;
					if (two_less != NULL) {
						_tmp61_ = one_less != NULL;
					} else {
						_tmp61_ = FALSE;
					}
					if (_tmp61_) {
						Tile* _tmp62_;
						Tile* _tmp63_;
						Tile* _tmp64_;
						Tile* _tmp65_;
						_tmp62_ = _g_object_ref0 (two_less);
						_tmp63_ = _tmp62_;
						_g_object_unref0 (tiles[0]);
						tiles[0] = _tmp63_;
						_tmp64_ = _g_object_ref0 (one_less);
						_tmp65_ = _tmp64_;
						_g_object_unref0 (tiles[1]);
						tiles[1] = _tmp65_;
					} else {
						gboolean _tmp66_ = FALSE;
						if (one_less != NULL) {
							_tmp66_ = one_more != NULL;
						} else {
							_tmp66_ = FALSE;
						}
						if (_tmp66_) {
							Tile* _tmp67_;
							Tile* _tmp68_;
							Tile* _tmp69_;
							Tile* _tmp70_;
							_tmp67_ = _g_object_ref0 (one_less);
							_tmp68_ = _tmp67_;
							_g_object_unref0 (tiles[0]);
							tiles[0] = _tmp68_;
							_tmp69_ = _g_object_ref0 (one_more);
							_tmp70_ = _tmp69_;
							_g_object_unref0 (tiles[1]);
							tiles[1] = _tmp70_;
						} else {
							gboolean _tmp71_ = FALSE;
							if (one_more != NULL) {
								_tmp71_ = two_more != NULL;
							} else {
								_tmp71_ = FALSE;
							}
							if (_tmp71_) {
								Tile* _tmp72_;
								Tile* _tmp73_;
								Tile* _tmp74_;
								Tile* _tmp75_;
								_tmp72_ = _g_object_ref0 (one_more);
								_tmp73_ = _tmp72_;
								_g_object_unref0 (tiles[0]);
								tiles[0] = _tmp73_;
								_tmp74_ = _g_object_ref0 (two_more);
								_tmp75_ = _tmp74_;
								_g_object_unref0 (tiles[1]);
								tiles[1] = _tmp75_;
							}
						}
					}
					_tmp77_ = tile_tiles_to_ints (tiles, tiles_length1, &_tmp76_);
					_tmp78_ = _tmp77_;
					_tmp78__length1 = _tmp76_;
					_tmp79_ = call_action_new (CALL_ACTION_CALL_ACTION_ENUM_CHI, _tmp78_, _tmp76_);
					_tmp80_ = _tmp79_;
					_tmp78_ = (g_free (_tmp78_), NULL);
					result = _tmp80_;
					tiles = (_vala_array_free (tiles, tiles_length1, (GDestroyNotify) g_object_unref), NULL);
					_g_object_unref0 (two_more);
					_g_object_unref0 (one_more);
					_g_object_unref0 (one_less);
					_g_object_unref0 (two_less);
					return result;
				}
			}
		}
	}
	_tmp81_ = call_action_new_none ();
	result = _tmp81_;
	return result;
}


TurnAction* bot_make_move (gint bot_level, ComputerPlayer* player) {
	TurnAction* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint32 _tmp2_;
	gpointer _tmp3_ = NULL;
	Tile* _tmp4_;
	guint8 _tmp5_;
	TurnAction* _tmp6_ = NULL;
	TurnAction* _tmp7_;
	gboolean _tmp8_ = FALSE;
	GeeArrayList* _tmp9_ = NULL;
	gboolean _tmp10_;
	GeeArrayList* _tmp22_ = NULL;
	GeeArrayList* _tmp23_ = NULL;
	GeeArrayList* tenpai_tiles;
	gboolean _tmp24_ = FALSE;
	gint _tmp25_;
	GeeArrayList* _tmp73_ = NULL;
	gint _tmp74_;
	g_return_val_if_fail (player != NULL, NULL);
	bot_delay ();
	_tmp0_ = player_get_hand ((Player*) player);
	_tmp1_ = environment_get_random ();
	_tmp2_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) 1);
	_tmp3_ = gee_abstract_list_get ((GeeAbstractList*) _tmp0_, (gint) _tmp2_);
	_tmp4_ = (Tile*) _tmp3_;
	_tmp5_ = tile_get_id (_tmp4_);
	_tmp6_ = turn_action_new_discard (_tmp5_);
	_tmp7_ = _tmp6_;
	_g_object_unref0 (_tmp4_);
	result = _tmp7_;
	return result;
	_tmp9_ = player_get_hand ((Player*) player);
	_tmp10_ = logic_winning_hand (_tmp9_);
	if (_tmp10_) {
		gboolean _tmp11_;
		_tmp11_ = logic_has_yaku ((Player*) player, NULL, FALSE, FALSE);
		_tmp8_ = _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		TurnAction* _tmp12_ = NULL;
		_tmp12_ = turn_action_new_tsumo ();
		result = _tmp12_;
		return result;
	} else {
		gboolean _tmp13_;
		_tmp13_ = player_get_in_riichi ((Player*) player);
		if (_tmp13_) {
			GeeArrayList* _tmp14_ = NULL;
			GeeArrayList* _tmp15_ = NULL;
			gint _tmp16_;
			gpointer _tmp17_ = NULL;
			Tile* _tmp18_;
			guint8 _tmp19_;
			TurnAction* _tmp20_ = NULL;
			TurnAction* _tmp21_;
			_tmp14_ = player_get_hand ((Player*) player);
			_tmp15_ = player_get_hand ((Player*) player);
			_tmp16_ = gee_collection_get_size ((GeeCollection*) _tmp15_);
			_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp16_ - 1);
			_tmp18_ = (Tile*) _tmp17_;
			_tmp19_ = tile_get_id (_tmp18_);
			_tmp20_ = turn_action_new_discard (_tmp19_);
			_tmp21_ = _tmp20_;
			_g_object_unref0 (_tmp18_);
			result = _tmp21_;
			return result;
		}
	}
	_tmp22_ = player_get_hand ((Player*) player);
	_tmp23_ = logic_can_tenpai (_tmp22_);
	tenpai_tiles = _tmp23_;
	_tmp25_ = gee_collection_get_size ((GeeCollection*) tenpai_tiles);
	if (_tmp25_ != 0) {
		gboolean _tmp26_;
		_tmp26_ = player_get_open_hand ((Player*) player);
		_tmp24_ = !_tmp26_;
	} else {
		_tmp24_ = FALSE;
	}
	if (_tmp24_) {
		gpointer _tmp27_ = NULL;
		Tile* _tmp28_;
		guint8 _tmp29_;
		TurnAction* _tmp30_ = NULL;
		TurnAction* _tmp31_;
		_tmp27_ = gee_abstract_list_get ((GeeAbstractList*) tenpai_tiles, 0);
		_tmp28_ = (Tile*) _tmp27_;
		_tmp29_ = tile_get_id (_tmp28_);
		_tmp30_ = turn_action_new_riichi (_tmp29_);
		_tmp31_ = _tmp30_;
		_g_object_unref0 (_tmp28_);
		result = _tmp31_;
		return result;
	} else {
		GeeArrayList* _tmp32_ = NULL;
		gboolean _tmp33_;
		_tmp32_ = player_get_hand ((Player*) player);
		_tmp33_ = logic_can_closed_kan (_tmp32_);
		if (_tmp33_) {
			Tile** _tmp34_ = NULL;
			Tile** kan;
			gint kan_length1;
			gint _kan_size_;
			_tmp34_ = g_new0 (Tile*, 4 + 1);
			kan = _tmp34_;
			kan_length1 = 4;
			_kan_size_ = 4;
			{
				GeeArrayList* _tmp35_ = NULL;
				GeeArrayList* _tmp36_;
				GeeArrayList* _t_list;
				gint _tmp37_;
				gint _t_size;
				gint _t_index;
				_tmp35_ = player_get_hand ((Player*) player);
				_tmp36_ = _g_object_ref0 (_tmp35_);
				_t_list = _tmp36_;
				_tmp37_ = gee_collection_get_size ((GeeCollection*) _t_list);
				_t_size = _tmp37_;
				_t_index = -1;
				while (TRUE) {
					gpointer _tmp38_ = NULL;
					Tile* t;
					gint count;
					_t_index = _t_index + 1;
					if (!(_t_index < _t_size)) {
						break;
					}
					_tmp38_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
					t = (Tile*) _tmp38_;
					count = 0;
					{
						GeeArrayList* _tmp39_ = NULL;
						GeeArrayList* _tmp40_;
						GeeArrayList* _o_list;
						gint _tmp41_;
						gint _o_size;
						gint _o_index;
						_tmp39_ = player_get_hand ((Player*) player);
						_tmp40_ = _g_object_ref0 (_tmp39_);
						_o_list = _tmp40_;
						_tmp41_ = gee_collection_get_size ((GeeCollection*) _o_list);
						_o_size = _tmp41_;
						_o_index = -1;
						while (TRUE) {
							gpointer _tmp42_ = NULL;
							Tile* o;
							gint _tmp43_;
							gint _tmp44_;
							_o_index = _o_index + 1;
							if (!(_o_index < _o_size)) {
								break;
							}
							_tmp42_ = gee_abstract_list_get ((GeeAbstractList*) _o_list, _o_index);
							o = (Tile*) _tmp42_;
							_tmp43_ = tile_get_tile_type (t);
							_tmp44_ = tile_get_tile_type (o);
							if (_tmp43_ == _tmp44_) {
								gint _tmp45_;
								Tile* _tmp46_;
								Tile* _tmp47_;
								_tmp45_ = count;
								count = _tmp45_ + 1;
								_tmp46_ = _g_object_ref0 (o);
								_tmp47_ = _tmp46_;
								_g_object_unref0 (kan[_tmp45_]);
								kan[_tmp45_] = _tmp47_;
							}
							if (count == 4) {
								gint _tmp48_;
								guint8* _tmp49_ = NULL;
								guint8* _tmp50_;
								gint _tmp50__length1;
								TurnAction* _tmp51_ = NULL;
								TurnAction* _tmp52_;
								_tmp49_ = tile_tiles_to_ints (kan, kan_length1, &_tmp48_);
								_tmp50_ = _tmp49_;
								_tmp50__length1 = _tmp48_;
								_tmp51_ = turn_action_new_closed_kan (_tmp50_, _tmp48_);
								_tmp52_ = _tmp51_;
								_tmp50_ = (g_free (_tmp50_), NULL);
								result = _tmp52_;
								_g_object_unref0 (o);
								_g_object_unref0 (_o_list);
								_g_object_unref0 (t);
								_g_object_unref0 (_t_list);
								kan = (_vala_array_free (kan, kan_length1, (GDestroyNotify) g_object_unref), NULL);
								return result;
							}
							_g_object_unref0 (o);
						}
						_g_object_unref0 (_o_list);
					}
					_g_object_unref0 (t);
				}
				_g_object_unref0 (_t_list);
			}
			kan = (_vala_array_free (kan, kan_length1, (GDestroyNotify) g_object_unref), NULL);
		} else {
			GeeArrayList* _tmp53_ = NULL;
			GeeArrayList* _tmp54_ = NULL;
			gboolean _tmp55_;
			_tmp53_ = player_get_hand ((Player*) player);
			_tmp54_ = player_get_pons ((Player*) player);
			_tmp55_ = logic_can_late_kan (_tmp53_, _tmp54_);
			if (_tmp55_) {
				{
					guint8 i;
					i = (guint8) 0;
					{
						gboolean _tmp56_;
						_tmp56_ = TRUE;
						while (TRUE) {
							GeeArrayList* _tmp57_ = NULL;
							gint _tmp58_;
							if (!_tmp56_) {
								i++;
							}
							_tmp56_ = FALSE;
							_tmp57_ = player_get_pons ((Player*) player);
							_tmp58_ = gee_collection_get_size ((GeeCollection*) _tmp57_);
							if (!(i < _tmp58_)) {
								break;
							}
							{
								GeeArrayList* _tmp59_ = NULL;
								GeeArrayList* _tmp60_;
								GeeArrayList* _t_list;
								gint _tmp61_;
								gint _t_size;
								gint _t_index;
								_tmp59_ = player_get_hand ((Player*) player);
								_tmp60_ = _g_object_ref0 (_tmp59_);
								_t_list = _tmp60_;
								_tmp61_ = gee_collection_get_size ((GeeCollection*) _t_list);
								_t_size = _tmp61_;
								_t_index = -1;
								while (TRUE) {
									gpointer _tmp62_ = NULL;
									Tile* t;
									gint _tmp63_;
									GeeArrayList* _tmp64_ = NULL;
									gpointer _tmp65_ = NULL;
									Pon* _tmp66_;
									Tile** _tmp67_ = NULL;
									gint _tmp68_;
									gint _tmp69_;
									gboolean _tmp70_;
									_t_index = _t_index + 1;
									if (!(_t_index < _t_size)) {
										break;
									}
									_tmp62_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
									t = (Tile*) _tmp62_;
									_tmp63_ = tile_get_tile_type (t);
									_tmp64_ = player_get_pons ((Player*) player);
									_tmp65_ = gee_abstract_list_get ((GeeAbstractList*) _tmp64_, (gint) i);
									_tmp66_ = (Pon*) _tmp65_;
									_tmp67_ = call_get_tiles ((Call*) _tmp66_, &_tmp68_);
									_tmp69_ = tile_get_tile_type (_tmp67_[0]);
									_tmp70_ = _tmp63_ == _tmp69_;
									_call_unref0 (_tmp66_);
									if (_tmp70_) {
										guint8 _tmp71_;
										TurnAction* _tmp72_ = NULL;
										_tmp71_ = tile_get_id (t);
										_tmp72_ = turn_action_new_late_kan (_tmp71_, i);
										result = _tmp72_;
										_g_object_unref0 (t);
										_g_object_unref0 (_t_list);
										return result;
									}
									_g_object_unref0 (t);
								}
								_g_object_unref0 (_t_list);
							}
						}
					}
				}
			}
		}
	}
	_tmp73_ = player_get_hand ((Player*) player);
	_tmp74_ = gee_collection_get_size ((GeeCollection*) _tmp73_);
	if (_tmp74_ != 0) {
		GeeArrayList* _tmp88_ = NULL;
		GRand* _tmp89_ = NULL;
		gint32 _tmp90_;
		gpointer _tmp91_ = NULL;
		Tile* _tmp92_;
		guint8 _tmp93_;
		TurnAction* _tmp94_ = NULL;
		TurnAction* _tmp95_;
		{
			GeeArrayList* _tmp75_ = NULL;
			GeeArrayList* _tmp76_;
			GeeArrayList* _tile_list;
			gint _tmp77_;
			gint _tile_size;
			gint _tile_index;
			_tmp75_ = player_get_hand ((Player*) player);
			_tmp76_ = _g_object_ref0 (_tmp75_);
			_tile_list = _tmp76_;
			_tmp77_ = gee_collection_get_size ((GeeCollection*) _tile_list);
			_tile_size = _tmp77_;
			_tile_index = -1;
			while (TRUE) {
				gpointer _tmp78_ = NULL;
				Tile* tile;
				gint count;
				gboolean _tmp85_ = FALSE;
				_tile_index = _tile_index + 1;
				if (!(_tile_index < _tile_size)) {
					break;
				}
				_tmp78_ = gee_abstract_list_get ((GeeAbstractList*) _tile_list, _tile_index);
				tile = (Tile*) _tmp78_;
				count = 0;
				{
					GeeArrayList* _tmp79_ = NULL;
					GeeArrayList* _tmp80_;
					GeeArrayList* _t_list;
					gint _tmp81_;
					gint _t_size;
					gint _t_index;
					_tmp79_ = player_get_hand ((Player*) player);
					_tmp80_ = _g_object_ref0 (_tmp79_);
					_t_list = _tmp80_;
					_tmp81_ = gee_collection_get_size ((GeeCollection*) _t_list);
					_t_size = _tmp81_;
					_t_index = -1;
					while (TRUE) {
						gpointer _tmp82_ = NULL;
						Tile* t;
						gint _tmp83_;
						gint _tmp84_;
						_t_index = _t_index + 1;
						if (!(_t_index < _t_size)) {
							break;
						}
						_tmp82_ = gee_abstract_list_get ((GeeAbstractList*) _t_list, _t_index);
						t = (Tile*) _tmp82_;
						_tmp83_ = tile_get_tile_type (tile);
						_tmp84_ = tile_get_tile_type (t);
						if (_tmp83_ == _tmp84_) {
							count++;
						}
						_g_object_unref0 (t);
					}
					_g_object_unref0 (_t_list);
				}
				if (count != 2) {
					_tmp85_ = count != 4;
				} else {
					_tmp85_ = FALSE;
				}
				if (_tmp85_) {
					guint8 _tmp86_;
					TurnAction* _tmp87_ = NULL;
					_tmp86_ = tile_get_id (tile);
					_tmp87_ = turn_action_new_discard (_tmp86_);
					result = _tmp87_;
					_g_object_unref0 (tile);
					_g_object_unref0 (_tile_list);
					return result;
				}
				_g_object_unref0 (tile);
			}
			_g_object_unref0 (_tile_list);
		}
		_tmp88_ = player_get_hand ((Player*) player);
		_tmp89_ = environment_get_random ();
		_tmp90_ = g_rand_int_range (_tmp89_, (gint32) 0, (gint32) 1);
		_tmp91_ = gee_abstract_list_get ((GeeAbstractList*) _tmp88_, (gint) _tmp90_);
		_tmp92_ = (Tile*) _tmp91_;
		_tmp93_ = tile_get_id (_tmp92_);
		_tmp94_ = turn_action_new_discard (_tmp93_);
		_tmp95_ = _tmp94_;
		_g_object_unref0 (_tmp92_);
		result = _tmp95_;
		return result;
	}
	result = NULL;
	return result;
}


static void bot_delay (void) {
	g_usleep (bot_decision_delay);
}


Bot* bot_construct (GType object_type) {
	Bot* self = NULL;
	self = (Bot*) g_type_create_instance (object_type);
	return self;
}


Bot* bot_new (void) {
	return bot_construct (TYPE_BOT);
}


static void value_bot_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_bot_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		bot_unref (value->data[0].v_pointer);
	}
}


static void value_bot_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = bot_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_bot_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_bot_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Bot* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = bot_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_bot_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Bot** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = bot_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_bot (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecBot* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_BOT), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_bot (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BOT), NULL);
	return value->data[0].v_pointer;
}


void value_set_bot (GValue* value, gpointer v_object) {
	Bot* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BOT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BOT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		bot_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		bot_unref (old);
	}
}


void value_take_bot (GValue* value, gpointer v_object) {
	Bot* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BOT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BOT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		bot_unref (old);
	}
}


static void bot_class_init (BotClass * klass) {
	bot_parent_class = g_type_class_peek_parent (klass);
	BOT_CLASS (klass)->finalize = bot_finalize;
}


static void bot_instance_init (Bot * self) {
	self->ref_count = 1;
}


static void bot_finalize (Bot* obj) {
	Bot * self;
	self = BOT (obj);
}


GType bot_get_type (void) {
	static volatile gsize bot_type_id__volatile = 0;
	if (g_once_init_enter (&bot_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_bot_init, value_bot_free_value, value_bot_copy_value, value_bot_peek_pointer, "p", value_bot_collect_value, "p", value_bot_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (BotClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bot_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Bot), 0, (GInstanceInitFunc) bot_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType bot_type_id;
		bot_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Bot", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&bot_type_id__volatile, bot_type_id);
	}
	return bot_type_id__volatile;
}


gpointer bot_ref (gpointer instance) {
	Bot* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void bot_unref (gpointer instance) {
	Bot* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		BOT_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



