/* GameStateTurnDecision.c generated by valac 0.12.0, the Vala compiler
 * generated from GameStateTurnDecision.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define TYPE_GAME_STATE_TURN_DECISION (game_state_turn_decision_get_type ())
#define GAME_STATE_TURN_DECISION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecision))
#define GAME_STATE_TURN_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecisionClass))
#define IS_GAME_STATE_TURN_DECISION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_TURN_DECISION))
#define IS_GAME_STATE_TURN_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_TURN_DECISION))
#define GAME_STATE_TURN_DECISION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecisionClass))

typedef struct _GameStateTurnDecision GameStateTurnDecision;
typedef struct _GameStateTurnDecisionClass GameStateTurnDecisionClass;
typedef struct _GameStateTurnDecisionPrivate GameStateTurnDecisionPrivate;

#define GAME_STATE_TURN_DECISION_TYPE_TURN_DECISION (game_state_turn_decision_turn_decision_get_type ())

#define TYPE_GAME_STATE_TILE (game_state_tile_get_type ())
#define GAME_STATE_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_TILE, GameStateTile))
#define GAME_STATE_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_TILE, GameStateTileClass))
#define IS_GAME_STATE_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_TILE))
#define IS_GAME_STATE_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_TILE))
#define GAME_STATE_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_TILE, GameStateTileClass))

typedef struct _GameStateTile GameStateTile;
typedef struct _GameStateTileClass GameStateTileClass;
#define _game_state_tile_unref0(var) ((var == NULL) ? NULL : (var = (game_state_tile_unref (var), NULL)))
typedef struct _ParamSpecGameStateTurnDecision ParamSpecGameStateTurnDecision;

struct _GameStateTurnDecision {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GameStateTurnDecisionPrivate * priv;
};

struct _GameStateTurnDecisionClass {
	GTypeClass parent_class;
	void (*finalize) (GameStateTurnDecision *self);
};

typedef enum  {
	GAME_STATE_TURN_DECISION_TURN_DECISION_TSUMO,
	GAME_STATE_TURN_DECISION_TURN_DECISION_DISCARD
} GameStateTurnDecisionTurnDecision;

struct _GameStateTurnDecisionPrivate {
	GameStateTurnDecisionTurnDecision _decision_type;
	GameStateTile* _tile;
};

struct _ParamSpecGameStateTurnDecision {
	GParamSpec parent_instance;
};


static gpointer game_state_turn_decision_parent_class = NULL;

gpointer game_state_turn_decision_ref (gpointer instance);
void game_state_turn_decision_unref (gpointer instance);
GParamSpec* param_spec_game_state_turn_decision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_turn_decision (GValue* value, gpointer v_object);
void value_take_game_state_turn_decision (GValue* value, gpointer v_object);
gpointer value_get_game_state_turn_decision (const GValue* value);
GType game_state_turn_decision_get_type (void) G_GNUC_CONST;
GType game_state_turn_decision_turn_decision_get_type (void) G_GNUC_CONST;
gpointer game_state_tile_ref (gpointer instance);
void game_state_tile_unref (gpointer instance);
GParamSpec* param_spec_game_state_tile (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_tile (GValue* value, gpointer v_object);
void value_take_game_state_tile (GValue* value, gpointer v_object);
gpointer value_get_game_state_tile (const GValue* value);
GType game_state_tile_get_type (void) G_GNUC_CONST;
#define GAME_STATE_TURN_DECISION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecisionPrivate))
enum  {
	GAME_STATE_TURN_DECISION_DUMMY_PROPERTY
};
GameStateTurnDecision* game_state_turn_decision_new (void);
GameStateTurnDecision* game_state_turn_decision_construct (GType object_type);
GameStateTurnDecisionTurnDecision game_state_turn_decision_get_DecisionType (GameStateTurnDecision* self);
GameStateTile* game_state_turn_decision_get_Tile (GameStateTurnDecision* self);
static void game_state_turn_decision_finalize (GameStateTurnDecision* obj);


GType game_state_turn_decision_turn_decision_get_type (void) {
	static volatile gsize game_state_turn_decision_turn_decision_type_id__volatile = 0;
	if (g_once_init_enter (&game_state_turn_decision_turn_decision_type_id__volatile)) {
		static const GEnumValue values[] = {{GAME_STATE_TURN_DECISION_TURN_DECISION_TSUMO, "GAME_STATE_TURN_DECISION_TURN_DECISION_TSUMO", "tsumo"}, {GAME_STATE_TURN_DECISION_TURN_DECISION_DISCARD, "GAME_STATE_TURN_DECISION_TURN_DECISION_DISCARD", "discard"}, {0, NULL, NULL}};
		GType game_state_turn_decision_turn_decision_type_id;
		game_state_turn_decision_turn_decision_type_id = g_enum_register_static ("GameStateTurnDecisionTurnDecision", values);
		g_once_init_leave (&game_state_turn_decision_turn_decision_type_id__volatile, game_state_turn_decision_turn_decision_type_id);
	}
	return game_state_turn_decision_turn_decision_type_id__volatile;
}


GameStateTurnDecision* game_state_turn_decision_construct (GType object_type) {
	GameStateTurnDecision* self = NULL;
	self = (GameStateTurnDecision*) g_type_create_instance (object_type);
	return self;
}


GameStateTurnDecision* game_state_turn_decision_new (void) {
	return game_state_turn_decision_construct (TYPE_GAME_STATE_TURN_DECISION);
}


GameStateTurnDecisionTurnDecision game_state_turn_decision_get_DecisionType (GameStateTurnDecision* self) {
	GameStateTurnDecisionTurnDecision result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_decision_type;
	return result;
}


GameStateTile* game_state_turn_decision_get_Tile (GameStateTurnDecision* self) {
	GameStateTile* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_tile;
	return result;
}


static void value_game_state_turn_decision_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_game_state_turn_decision_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		game_state_turn_decision_unref (value->data[0].v_pointer);
	}
}


static void value_game_state_turn_decision_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = game_state_turn_decision_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_game_state_turn_decision_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_game_state_turn_decision_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GameStateTurnDecision* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = game_state_turn_decision_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_game_state_turn_decision_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GameStateTurnDecision** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = game_state_turn_decision_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_game_state_turn_decision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecGameStateTurnDecision* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_GAME_STATE_TURN_DECISION), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_game_state_turn_decision (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE_TURN_DECISION), NULL);
	return value->data[0].v_pointer;
}


void value_set_game_state_turn_decision (GValue* value, gpointer v_object) {
	GameStateTurnDecision* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE_TURN_DECISION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GAME_STATE_TURN_DECISION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		game_state_turn_decision_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		game_state_turn_decision_unref (old);
	}
}


void value_take_game_state_turn_decision (GValue* value, gpointer v_object) {
	GameStateTurnDecision* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE_TURN_DECISION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GAME_STATE_TURN_DECISION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		game_state_turn_decision_unref (old);
	}
}


static void game_state_turn_decision_class_init (GameStateTurnDecisionClass * klass) {
	game_state_turn_decision_parent_class = g_type_class_peek_parent (klass);
	GAME_STATE_TURN_DECISION_CLASS (klass)->finalize = game_state_turn_decision_finalize;
	g_type_class_add_private (klass, sizeof (GameStateTurnDecisionPrivate));
}


static void game_state_turn_decision_instance_init (GameStateTurnDecision * self) {
	self->priv = GAME_STATE_TURN_DECISION_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void game_state_turn_decision_finalize (GameStateTurnDecision* obj) {
	GameStateTurnDecision * self;
	self = GAME_STATE_TURN_DECISION (obj);
	_game_state_tile_unref0 (self->priv->_tile);
}


GType game_state_turn_decision_get_type (void) {
	static volatile gsize game_state_turn_decision_type_id__volatile = 0;
	if (g_once_init_enter (&game_state_turn_decision_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_game_state_turn_decision_init, value_game_state_turn_decision_free_value, value_game_state_turn_decision_copy_value, value_game_state_turn_decision_peek_pointer, "p", value_game_state_turn_decision_collect_value, "p", value_game_state_turn_decision_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GameStateTurnDecisionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) game_state_turn_decision_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GameStateTurnDecision), 0, (GInstanceInitFunc) game_state_turn_decision_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType game_state_turn_decision_type_id;
		game_state_turn_decision_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GameStateTurnDecision", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&game_state_turn_decision_type_id__volatile, game_state_turn_decision_type_id);
	}
	return game_state_turn_decision_type_id__volatile;
}


gpointer game_state_turn_decision_ref (gpointer instance) {
	GameStateTurnDecision* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void game_state_turn_decision_unref (gpointer instance) {
	GameStateTurnDecision* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GAME_STATE_TURN_DECISION_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



