/* ServerPlayer.c generated by valac 0.12.0, the Vala compiler
 * generated from ServerPlayer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define TYPE_SERVER_PLAYER (server_player_get_type ())
#define SERVER_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVER_PLAYER, ServerPlayer))
#define SERVER_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVER_PLAYER, ServerPlayerClass))
#define IS_SERVER_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVER_PLAYER))
#define IS_SERVER_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVER_PLAYER))
#define SERVER_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVER_PLAYER, ServerPlayerClass))

typedef struct _ServerPlayer ServerPlayer;
typedef struct _ServerPlayerClass ServerPlayerClass;
typedef struct _ServerPlayerPrivate ServerPlayerPrivate;

#define SERVER_PLAYER_TYPE_STATE (server_player_state_get_type ())

#define TYPE_GAME_STATE_PLAYER (game_state_player_get_type ())
#define GAME_STATE_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_PLAYER, GameStatePlayer))
#define GAME_STATE_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_PLAYER, GameStatePlayerClass))
#define IS_GAME_STATE_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_PLAYER))
#define IS_GAME_STATE_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_PLAYER))
#define GAME_STATE_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_PLAYER, GameStatePlayerClass))

typedef struct _GameStatePlayer GameStatePlayer;
typedef struct _GameStatePlayerClass GameStatePlayerClass;

#define TYPE_GAME_STATE_TURN_DECISION (game_state_turn_decision_get_type ())
#define GAME_STATE_TURN_DECISION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecision))
#define GAME_STATE_TURN_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecisionClass))
#define IS_GAME_STATE_TURN_DECISION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_TURN_DECISION))
#define IS_GAME_STATE_TURN_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_TURN_DECISION))
#define GAME_STATE_TURN_DECISION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_TURN_DECISION, GameStateTurnDecisionClass))

typedef struct _GameStateTurnDecision GameStateTurnDecision;
typedef struct _GameStateTurnDecisionClass GameStateTurnDecisionClass;

#define TYPE_GAME_STATE_CALL_DECISION (game_state_call_decision_get_type ())
#define GAME_STATE_CALL_DECISION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_CALL_DECISION, GameStateCallDecision))
#define GAME_STATE_CALL_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_CALL_DECISION, GameStateCallDecisionClass))
#define IS_GAME_STATE_CALL_DECISION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_CALL_DECISION))
#define IS_GAME_STATE_CALL_DECISION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_CALL_DECISION))
#define GAME_STATE_CALL_DECISION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_CALL_DECISION, GameStateCallDecisionClass))

typedef struct _GameStateCallDecision GameStateCallDecision;
typedef struct _GameStateCallDecisionClass GameStateCallDecisionClass;

#define TYPE_GAME_STATE_TILE (game_state_tile_get_type ())
#define GAME_STATE_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE_TILE, GameStateTile))
#define GAME_STATE_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE_TILE, GameStateTileClass))
#define IS_GAME_STATE_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE_TILE))
#define IS_GAME_STATE_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE_TILE))
#define GAME_STATE_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE_TILE, GameStateTileClass))

typedef struct _GameStateTile GameStateTile;
typedef struct _GameStateTileClass GameStateTileClass;
typedef struct _ParamSpecServerPlayer ParamSpecServerPlayer;

struct _ServerPlayer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ServerPlayerPrivate * priv;
};

struct _ServerPlayerClass {
	GTypeClass parent_class;
	void (*finalize) (ServerPlayer *self);
};

typedef enum  {
	SERVER_PLAYER_STATE_PLAYER,
	SERVER_PLAYER_STATE_SPECTATOR
} ServerPlayerState;

struct _ServerPlayerPrivate {
	ServerPlayerState _state;
	gboolean _ready;
};

struct _ParamSpecServerPlayer {
	GParamSpec parent_instance;
};


static gpointer server_player_parent_class = NULL;

gpointer server_player_ref (gpointer instance);
void server_player_unref (gpointer instance);
GParamSpec* param_spec_server_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_server_player (GValue* value, gpointer v_object);
void value_take_server_player (GValue* value, gpointer v_object);
gpointer value_get_server_player (const GValue* value);
GType server_player_get_type (void) G_GNUC_CONST;
GType server_player_state_get_type (void) G_GNUC_CONST;
#define SERVER_PLAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SERVER_PLAYER, ServerPlayerPrivate))
enum  {
	SERVER_PLAYER_DUMMY_PROPERTY
};
ServerPlayer* server_player_new (void);
ServerPlayer* server_player_construct (GType object_type);
static void server_player_set_ready (ServerPlayer* self, gboolean value);
gpointer game_state_player_ref (gpointer instance);
void game_state_player_unref (gpointer instance);
GParamSpec* param_spec_game_state_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_player (GValue* value, gpointer v_object);
void value_take_game_state_player (GValue* value, gpointer v_object);
gpointer value_get_game_state_player (const GValue* value);
GType game_state_player_get_type (void) G_GNUC_CONST;
gpointer game_state_turn_decision_ref (gpointer instance);
void game_state_turn_decision_unref (gpointer instance);
GParamSpec* param_spec_game_state_turn_decision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_turn_decision (GValue* value, gpointer v_object);
void value_take_game_state_turn_decision (GValue* value, gpointer v_object);
gpointer value_get_game_state_turn_decision (const GValue* value);
GType game_state_turn_decision_get_type (void) G_GNUC_CONST;
void server_player_game_turn_decision (ServerPlayer* self, GameStatePlayer* player, GameStateTurnDecision* decision);
gpointer game_state_call_decision_ref (gpointer instance);
void game_state_call_decision_unref (gpointer instance);
GParamSpec* param_spec_game_state_call_decision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_call_decision (GValue* value, gpointer v_object);
void value_take_game_state_call_decision (GValue* value, gpointer v_object);
gpointer value_get_game_state_call_decision (const GValue* value);
GType game_state_call_decision_get_type (void) G_GNUC_CONST;
void server_player_game_call_decision (ServerPlayer* self, GameStatePlayer* player, GameStateCallDecision* decision);
gpointer game_state_tile_ref (gpointer instance);
void game_state_tile_unref (gpointer instance);
GParamSpec* param_spec_game_state_tile (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state_tile (GValue* value, gpointer v_object);
void value_take_game_state_tile (GValue* value, gpointer v_object);
gpointer value_get_game_state_tile (const GValue* value);
GType game_state_tile_get_type (void) G_GNUC_CONST;
void server_player_game_draw_tile (ServerPlayer* self, GameStatePlayer* player, GameStateTile* tile);
void server_player_game_draw_hidden (ServerPlayer* self, GameStatePlayer* player);
ServerPlayerState server_player_get_state (ServerPlayer* self);
static void server_player_set_state (ServerPlayer* self, ServerPlayerState value);
gboolean server_player_get_ready (ServerPlayer* self);
static void g_cclosure_user_marshal_VOID__SERVER_PLAYER (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void server_player_finalize (ServerPlayer* obj);


GType server_player_state_get_type (void) {
	static volatile gsize server_player_state_type_id__volatile = 0;
	if (g_once_init_enter (&server_player_state_type_id__volatile)) {
		static const GEnumValue values[] = {{SERVER_PLAYER_STATE_PLAYER, "SERVER_PLAYER_STATE_PLAYER", "player"}, {SERVER_PLAYER_STATE_SPECTATOR, "SERVER_PLAYER_STATE_SPECTATOR", "spectator"}, {0, NULL, NULL}};
		GType server_player_state_type_id;
		server_player_state_type_id = g_enum_register_static ("ServerPlayerState", values);
		g_once_init_leave (&server_player_state_type_id__volatile, server_player_state_type_id);
	}
	return server_player_state_type_id__volatile;
}


ServerPlayer* server_player_construct (GType object_type) {
	ServerPlayer* self = NULL;
	self = (ServerPlayer*) g_type_create_instance (object_type);
	server_player_set_ready (self, TRUE);
	return self;
}


ServerPlayer* server_player_new (void) {
	return server_player_construct (TYPE_SERVER_PLAYER);
}


void server_player_game_turn_decision (ServerPlayer* self, GameStatePlayer* player, GameStateTurnDecision* decision) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	g_return_if_fail (decision != NULL);
}


void server_player_game_call_decision (ServerPlayer* self, GameStatePlayer* player, GameStateCallDecision* decision) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	g_return_if_fail (decision != NULL);
}


void server_player_game_draw_tile (ServerPlayer* self, GameStatePlayer* player, GameStateTile* tile) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	g_return_if_fail (tile != NULL);
}


void server_player_game_draw_hidden (ServerPlayer* self, GameStatePlayer* player) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
}


ServerPlayerState server_player_get_state (ServerPlayer* self) {
	ServerPlayerState result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_state;
	return result;
}


static void server_player_set_state (ServerPlayer* self, ServerPlayerState value) {
	g_return_if_fail (self != NULL);
	self->priv->_state = value;
}


gboolean server_player_get_ready (ServerPlayer* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_ready;
	return result;
}


static void server_player_set_ready (ServerPlayer* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_ready = value;
}


static void g_cclosure_user_marshal_VOID__SERVER_PLAYER (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__SERVER_PLAYER) (gpointer data1, gpointer arg_1, gpointer data2);
	register GMarshalFunc_VOID__SERVER_PLAYER callback;
	register GCClosure * cc;
	register gpointer data1, data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 2);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__SERVER_PLAYER) (marshal_data ? marshal_data : cc->callback);
	callback (data1, value_get_server_player (param_values + 1), data2);
}


static void g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION) (gpointer data1, gpointer arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION callback;
	register GCClosure * cc;
	register gpointer data1, data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION) (marshal_data ? marshal_data : cc->callback);
	callback (data1, value_get_server_player (param_values + 1), value_get_game_state_turn_decision (param_values + 2), data2);
}


static void g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION) (gpointer data1, gpointer arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION callback;
	register GCClosure * cc;
	register gpointer data1, data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION) (marshal_data ? marshal_data : cc->callback);
	callback (data1, value_get_server_player (param_values + 1), value_get_game_state_call_decision (param_values + 2), data2);
}


static void value_server_player_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_server_player_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		server_player_unref (value->data[0].v_pointer);
	}
}


static void value_server_player_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = server_player_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_server_player_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_server_player_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ServerPlayer* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = server_player_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_server_player_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ServerPlayer** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = server_player_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_server_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecServerPlayer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_SERVER_PLAYER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_server_player (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SERVER_PLAYER), NULL);
	return value->data[0].v_pointer;
}


void value_set_server_player (GValue* value, gpointer v_object) {
	ServerPlayer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SERVER_PLAYER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_SERVER_PLAYER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		server_player_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		server_player_unref (old);
	}
}


void value_take_server_player (GValue* value, gpointer v_object) {
	ServerPlayer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SERVER_PLAYER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_SERVER_PLAYER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		server_player_unref (old);
	}
}


static void server_player_class_init (ServerPlayerClass * klass) {
	server_player_parent_class = g_type_class_peek_parent (klass);
	SERVER_PLAYER_CLASS (klass)->finalize = server_player_finalize;
	g_type_class_add_private (klass, sizeof (ServerPlayerPrivate));
	g_signal_new ("disconnected", TYPE_SERVER_PLAYER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__SERVER_PLAYER, G_TYPE_NONE, 1, TYPE_SERVER_PLAYER);
	g_signal_new ("player_turn_decision", TYPE_SERVER_PLAYER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_TURN_DECISION, G_TYPE_NONE, 2, TYPE_SERVER_PLAYER, TYPE_GAME_STATE_TURN_DECISION);
	g_signal_new ("player_call_decision", TYPE_SERVER_PLAYER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__SERVER_PLAYER_GAME_STATE_CALL_DECISION, G_TYPE_NONE, 2, TYPE_SERVER_PLAYER, TYPE_GAME_STATE_CALL_DECISION);
}


static void server_player_instance_init (ServerPlayer * self) {
	self->priv = SERVER_PLAYER_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void server_player_finalize (ServerPlayer* obj) {
	ServerPlayer * self;
	self = SERVER_PLAYER (obj);
}


GType server_player_get_type (void) {
	static volatile gsize server_player_type_id__volatile = 0;
	if (g_once_init_enter (&server_player_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_server_player_init, value_server_player_free_value, value_server_player_copy_value, value_server_player_peek_pointer, "p", value_server_player_collect_value, "p", value_server_player_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ServerPlayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) server_player_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ServerPlayer), 0, (GInstanceInitFunc) server_player_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType server_player_type_id;
		server_player_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ServerPlayer", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&server_player_type_id__volatile, server_player_type_id);
	}
	return server_player_type_id__volatile;
}


gpointer server_player_ref (gpointer instance) {
	ServerPlayer* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void server_player_unref (gpointer instance) {
	ServerPlayer* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SERVER_PLAYER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



